import os, re, json

SRC = r"C:\developer\GIT\SuperBuilder_AI\SuperBuilder_AI\src"
ROOT = r"C:\developer\GIT\SuperBuilder_AI\SuperBuilder_AI"

# 提取 namespace：支持块式 `namespace X {` 与文件作用域 `namespace X;`
NS_RE = re.compile(r'^\s*namespace\s+([A-Za-z0-9_.]+)\s*[{;]', re.M)

def read_text(p):
    # utf-8-sig 自动剔除 BOM
    with open(p, 'r', encoding='utf-8-sig', errors='replace') as f:
        return f.read()

# 1) 目录 -> 命名空间(计数)
dir_ns = {}
# 2) 命名空间 -> 目录(计数)
ns_dirs = {}
# 3) 无命名空间文件
no_ns = []

for base, dirs, files in os.walk(SRC):
    for fn in files:
        if not fn.endswith('.cs'):
            continue
        fp = os.path.join(base, fn)
        try:
            txt = read_text(fp)
        except Exception as e:
            no_ns.append((fp, f'read-error:{e}'))
            continue
        # 跳过 *.Designer.cs 与 <auto-generated>
        if 'auto-generated' in txt[:400] or fn.endswith('.Designer.cs'):
            continue
        m = NS_RE.search(txt)
        if not m:
            no_ns.append((fp, 'no-namespace'))
            continue
        ns = m.group(1)
        rel_dir = os.path.relpath(base, SRC).replace('\\', '/')
        dir_ns.setdefault(rel_dir, {}).setdefault(ns, 0)
        dir_ns[rel_dir][ns] += 1
        ns_dirs.setdefault(ns, {}).setdefault(rel_dir, 0)
        ns_dirs[ns][rel_dir] += 1

# 输出：目录含多个命名空间
print("=" * 80)
print("A. 目录 -> 命名空间（仅列出含 >1 命名空间 或 命名空间与目录名明显不符的目录）")
print("=" * 80)
multi = {d: ns for d, ns in dir_ns.items() if len(ns) > 1}
for d in sorted(multi):
    print(f"\n[{d}]  -> {len(multi[d])} namespaces")
    for ns, c in sorted(multi[d].items(), key=lambda x: -x[1]):
        print(f"    {ns}  (x{c})")

print("\n" + "=" * 80)
print("B. 命名空间 -> 目录（仅列出跨 >1 目录 的命名空间，即命名空间碰撞）")
print("=" * 80)
cross = {ns: ds for ns, ds in ns_dirs.items() if len(ds) > 1}
for ns in sorted(cross):
    print(f"\n{ns}  -> 跨 {len(cross[ns])} 目录:")
    for d, c in sorted(cross[ns].items(), key=lambda x: -x[1]):
        print(f"    {d}  (x{c})")

print("\n" + "=" * 80)
print("C. 无命名空间文件（排除 auto-generated/Designer）计数:", len(no_ns))
print("=" * 80)
for fp, reason in no_ns[:50]:
    print(f"    {reason}: {os.path.relpath(fp, ROOT)}")

# 汇总数字
total_files = sum(sum(ns.values()) for ns in dir_ns.values())
print("\n--- 汇总 ---")
print(f"分析 .cs 文件(有效): {total_files}")
print(f"目录总数: {len(dir_ns)}")
print(f"命名空间总数(去重): {len(ns_dirs)}")
print(f"含多命名空间的目录数: {len(multi)}")
print(f"跨多目录的命名空间数: {len(cross)}")
print(f"无命名空间文件数: {len(no_ns)}")
