using Microsoft.EntityFrameworkCore;
using SuperBuilder_AI.Services.BI.Evaluation;
using SuperBuilder_AI.Configuration;
using SuperBuilder_AI.Data;
using SuperBuilder_AI.Infrastructure.Database;
using SuperBuilder_AI.Interfaces;
using SuperBuilder_AI.Interfaces.BI;
using SuperBuilder_AI.Interfaces.BI.Evaluation;
using SuperBuilder_AI.Interfaces.Database;
using SuperBuilder_AI.Services;
using SuperBuilder_AI.Services.BI;
using SuperBuilder_AI.Services.BI.Planning;
using SuperBuilder_AI.Services.Database;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllersWithViews();
builder.Services.AddDbContext<SuperBIContext>(options => options.UseSqlServer(builder.Configuration.GetConnectionString("SuperBI")));
builder.Services.AddHttpClient<IQwenService, QwenService>(client => { client.Timeout = TimeSpan.FromMinutes(5); client.DefaultRequestHeaders.Add("Accept", "application/json"); });
builder.Services.Configure<QdrantOptions>(builder.Configuration.GetSection("Qdrant"));
builder.Services.Configure<EmbeddingOptions>(builder.Configuration.GetSection("Embedding"));
builder.Services.AddScoped<IDataSourceMetadataReader, MySqlMetadataReader>();
builder.Services.AddScoped<MetadataScannerService>();
builder.Services.AddScoped<IMetadataSearchTextBuilder, MetadataSearchTextBuilder>();
builder.Services.AddScoped<IMetadataPromptBuilder, MetadataPromptBuilder>();
builder.Services.AddHttpClient<IEmbeddingService, QwenEmbeddingService>(client => { client.Timeout = TimeSpan.FromSeconds(120); client.DefaultRequestHeaders.Add("Accept", "application/json"); });
builder.Services.AddScoped<IQdrantService, QdrantService>();
builder.Services.AddScoped<IMetadataVectorService, MetadataVectorService>();
builder.Services.AddScoped<IMetadataVectorIndexService, MetadataVectorIndexService>();
builder.Services.AddScoped<IMetadataSemanticService, MetadataSemanticService>();
builder.Services.AddScoped<IMetadataSemanticSearchService, MetadataSemanticSearchService>();
builder.Services.AddScoped<IMetadataContextBuilder, MetadataContextBuilder>();
builder.Services.AddScoped<QueryPlanValidator>();
builder.Services.AddScoped<QueryIntentNormalizer>();
builder.Services.AddScoped<IQueryUnderstandingService, QueryUnderstandingService>();
builder.Services.AddScoped<IQueryJoinInferenceService, QueryJoinInferenceService>();
builder.Services.AddScoped<IQueryPlanBuilder, QueryPlanBuilder>();
builder.Services.AddScoped<IQueryPlanContextBuilder, QueryPlanContextBuilder>();
builder.Services.AddScoped<IResultUnderstandingService, ResultUnderstandingService>();
builder.Services.AddScoped<IBIConversationService, BIConversationService>();
builder.Services.AddScoped<ISqlDialectResolver, SqlDialectResolver>();
builder.Services.AddScoped<QueryPlanMetadataValidator>();
builder.Services.AddScoped<QuerySemanticValidator>();
builder.Services.AddScoped<IQueryPlanRepairService, QueryPlanRepairService>();
builder.Services.AddScoped<IQueryPlanValidationPipeline, QueryPlanValidationPipeline>();
builder.Services.AddScoped<IQueryPlanConfidenceService, QueryPlanConfidenceService>();
builder.Services.AddScoped<IQueryPlanDecisionGate, QueryPlanDecisionGate>();
builder.Services.AddScoped<IQueryPlanExplainabilityService, QueryPlanExplainabilityService>();
builder.Services.AddScoped<GoldenQueryDatasetSerializer>();
builder.Services.AddScoped<SemanticApplicabilityEvaluator>();
builder.Services.AddScoped<QueryPlanEvaluationGate>();
builder.Services.AddScoped<QueryPlanEvaluator>();
builder.Services.AddScoped<QueryPlanMetricScoringService>();
builder.Services.AddScoped<QueryPlanEvaluationScoringService>();
builder.Services.AddScoped<QueryPlanEvaluationConfidenceEvidenceAdapter>();
builder.Services.AddScoped<QueryPlanEvaluationConfidenceService>();
builder.Services.AddScoped<GoldenConfidenceCalibrationEvaluator>();
builder.Services.AddScoped<GoldenConfidenceCalibrationRunner>();
builder.Services.AddScoped<GoldenDatasetCoverageAnalyzer>();
builder.Services.AddScoped<GoldenDatasetQualityGate>();
builder.Services.AddScoped<GoldenBaselineReleaseService>();
builder.Services.AddSingleton<IGoldenBaselineRegistry, GoldenBaselineRegistry>();
builder.Services.AddSingleton<IGoldenBaselinePersistence, InMemoryGoldenBaselinePersistence>();
builder.Services.AddScoped<GoldenBaselinePersistenceService>();
builder.Services.AddScoped<GoldenBaselineLifecycleValidator>();
builder.Services.AddScoped<GoldenDatasetRunner>();
builder.Services.AddScoped<GoldenDatasetRegressionEvaluator>();
builder.Services.AddScoped<GoldenDatasetRuntimeService>();
builder.Services.AddScoped<IDataSourceConnectionFactory, DataSourceConnectionFactory>();
builder.Services.AddScoped<ISqlQueryBuilder, SqlQueryBuilder>();
builder.Services.AddScoped<IQueryExecutionService, QueryExecutionService>();
builder.Services.AddScoped<ISqlDialect, SqlServerDialect>();
builder.Services.AddScoped<ISqlDialect, MySqlDialect>();
builder.Services.AddScoped<ISqlDialect, PostgreSqlDialect>();
builder.Services.AddScoped<SqlDialectResolver>();

var app = builder.Build();
if (!app.Environment.IsDevelopment()) { app.UseExceptionHandler("/Home/Error"); app.UseHsts(); }
app.UseHttpsRedirection();
app.UseRouting();
app.UseAuthorization();
app.MapStaticAssets();
app.MapControllerRoute(name: "default", pattern: "{controller=Home}/{action=Index}/{id?}").WithStaticAssets();
app.Run();