// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperBulider_AI.Data;

#nullable disable

namespace SuperBulider_AI.Migrations
{
    [DbContext(typeof(SuperBIContext))]
    [Migration("20260811082322_Phase145SemanticOptimization2")]
    partial class Phase145SemanticOptimization2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("连接字符串");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DbType")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("数据库类型");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("DataSources", t =>
                        {
                            t.HasComment("数据源");
                        });
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessKey")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段业务唯一标识");

                    b.Property<string>("ColumnComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<long?>("Length")
                        .HasColumnType("bigint");

                    b.Property<long?>("MetadataTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段Embedding文本");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant字段向量ID");

                    b.HasKey("Id");

                    b.HasIndex("MetadataTableId", "ColumnName")
                        .IsUnique()
                        .HasFilter("[MetadataTableId] IS NOT NULL AND [ColumnName] IS NOT NULL");

                    b.ToTable("MetadataColumns", t =>
                        {
                            t.HasComment("元数据字段");
                        });
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataLearningRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Correct")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LearningRecords", t =>
                        {
                            t.HasComment("学习记录");
                        });
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataSemantic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务域");

                    b.Property<string>("BusinessMeaning")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务含义");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleQuestions")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("示例问题");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("关键词");

                    b.Property<long?>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("语义Embedding文本");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("来源");

                    b.Property<string>("Synonyms")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("同义词");

                    b.Property<int?>("VectorDimension")
                        .HasColumnType("int");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant语义向量ID");

                    b.HasKey("Id");

                    b.HasIndex("MetadataColumnId")
                        .IsUnique()
                        .HasFilter("[MetadataColumnId] IS NOT NULL");

                    b.ToTable("MetadataSemantics", t =>
                        {
                            t.HasComment("字段AI语义");
                        });
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Embedding文本");

                    b.Property<string>("TableComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int?>("VectorDimension")
                        .HasColumnType("int");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant向量ID");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "TableName")
                        .IsUnique()
                        .HasFilter("[TableName] IS NOT NULL");

                    b.ToTable("MetadataTables", t =>
                        {
                            t.HasComment("元数据表");
                        });
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Organization.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasComment("是否启用");

                    b.Property<string>("TenantCode")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("租户编码");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("租户名称");

                    b.HasKey("Id");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasFilter("[TenantCode] IS NOT NULL");

                    b.ToTable("Tenants", t =>
                        {
                            t.HasComment("租户");
                        });
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.DataSource", b =>
                {
                    b.HasOne("SuperBulider_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany("DataSources")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.HasOne("SuperBulider_AI.Models.Metadata.MetadataTable", "MetadataTable")
                        .WithMany("Columns")
                        .HasForeignKey("MetadataTableId");

                    b.Navigation("MetadataTable");
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataSemantic", b =>
                {
                    b.HasOne("SuperBulider_AI.Models.Metadata.MetadataColumn", "MetadataColumn")
                        .WithOne("Semantic")
                        .HasForeignKey("SuperBulider_AI.Models.Metadata.MetadataSemantic", "MetadataColumnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MetadataColumn");
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.HasOne("SuperBulider_AI.Models.Metadata.DataSource", "DataSource")
                        .WithMany("Tables")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.DataSource", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.Navigation("Semantic");
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("SuperBulider_AI.Models.Organization.Tenant", b =>
                {
                    b.Navigation("DataSources");
                });
#pragma warning restore 612, 618
        }
    }
}
