using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SuperBuilder_AI.Data;
using SuperBuilder_AI.Interfaces.Platform;
using SuperBuilder_AI.Models.Localization;

namespace SuperBuilder_AI.Services.Platform;

/// <summary>平台本地化目录（UiLanguage / UiTextResource）幂等种子，可在启动序列中调用。</summary>
public interface ILocalizationSeedService
{
    Task EnsureSeedAsync(CancellationToken ct = default);
}

/// <summary>
/// 从平台内置区域初始化数据库维护的语言目录与默认界面文案。
/// 与 <c>LocalizationController</c> 此前懒加载的种植逻辑等价，便于在启动顺序中固定执行
/// （M0-05：顺序 Schema → Identity/Permission → UiLanguage/Text → 默认策略/主题 → Bootstrap）。
/// </summary>
public sealed class LocalizationSeedService : ILocalizationSeedService
{
    private readonly SuperBIContext _db;
    private readonly ILocalizationService _localization;

    public LocalizationSeedService(SuperBIContext db, ILocalizationService localization)
    {
        _db = db;
        _localization = localization;
    }

    public async Task EnsureSeedAsync(CancellationToken ct = default)
    {
        var locales = _localization.SupportedLocales.ToList();
        var existingLanguages = await _db.UiLanguages.Select(x => x.Culture).ToListAsync(ct);
        _db.UiLanguages.AddRange(locales
            .Where(x => !existingLanguages.Contains(x.Culture, StringComparer.OrdinalIgnoreCase))
            .Select((x, i) => new UiLanguage
            {
                Culture = x.Culture,
                DisplayName = x.DisplayName,
                NativeName = x.DisplayName,
                Enabled = true,
                SortOrder = existingLanguages.Count + i,
            }));

        // M3-G0：补全全部 5 种文化的平台基线（原 14 键译文 + Validation/Error/Empty/Loading 键），
        // 键集合与 <see cref="ResourceKeys"/> 登记保持一致。
        var defaults = new Dictionary<string, Dictionary<string, string>>
        {
            ["zh-CN"] = new()
            {
                ["Common.Login"] = "登录", ["Common.Confirm"] = "确认", ["Common.Cancel"] = "取消",
                ["Common.Save"] = "保存", ["Common.Close"] = "关闭", ["Document.OutboundOrder"] = "出库单",
                ["Login.Title"] = "登录 / 租户选择", ["Login.Username"] = "用户名", ["Login.Password"] = "口令",
                ["Login.TenantId"] = "租户 ID", ["Login.Tagline"] = "自然语言驱动的智能问数平台 —— 对话即分析，所见即洞察。",
                ["App.Subtitle"] = "智能问数平台", ["Common.Settings"] = "个人设置", ["Common.Logout"] = "退出登录",
                ["Common.Loading"] = "加载中…",
                ["Validation.Required"] = "此项为必填。", ["Validation.Email"] = "请输入有效的邮箱地址。", ["Validation.Format"] = "格式不正确。",
                ["Error.Generic"] = "发生错误，请稍后重试。", ["Error.NotFound"] = "未找到请求的资源。", ["Empty.NoData"] = "暂无数据。",
                ["Nav.Dashboard"] = "仪表盘", ["Nav.Ask"] = "问数", ["Nav.DataSources"] = "数据源", ["Nav.Admin"] = "管理",
                ["Accessibility.SkipToContent"] = "跳到主内容", ["Theme.Light"] = "浅色", ["Theme.Dark"] = "深色",
            },
            ["zh-TW"] = new()
            {
                ["Common.Login"] = "登入", ["Common.Confirm"] = "確認", ["Common.Cancel"] = "取消",
                ["Common.Save"] = "儲存", ["Common.Close"] = "關閉", ["Document.OutboundOrder"] = "出貨單",
                ["Login.Title"] = "登入 / 選擇租戶", ["Login.Username"] = "使用者名稱", ["Login.Password"] = "密碼",
                ["Login.TenantId"] = "租戶 ID", ["Login.Tagline"] = "以自然語言驅動的智能問數平台 —— 對話即分析，所見即洞察。",
                ["App.Subtitle"] = "智能問數平台", ["Common.Settings"] = "個人設定", ["Common.Logout"] = "登出",
                ["Common.Loading"] = "載入中…",
                ["Validation.Required"] = "此項為必填。", ["Validation.Email"] = "請輸入有效的電子郵件地址。", ["Validation.Format"] = "格式不正確。",
                ["Error.Generic"] = "發生錯誤，請稍後再試。", ["Error.NotFound"] = "找不到要求的資源。", ["Empty.NoData"] = "暫無資料。",
                ["Nav.Dashboard"] = "儀表板", ["Nav.Ask"] = "問數", ["Nav.DataSources"] = "資料來源", ["Nav.Admin"] = "管理",
                ["Accessibility.SkipToContent"] = "跳到主內容", ["Theme.Light"] = "淺色", ["Theme.Dark"] = "深色",
            },
            ["en-US"] = new()
            {
                ["Common.Login"] = "Sign in", ["Common.Confirm"] = "Confirm", ["Common.Cancel"] = "Cancel",
                ["Common.Save"] = "Save", ["Common.Close"] = "Close", ["Document.OutboundOrder"] = "Outbound order",
                ["Login.Title"] = "Sign in / Select tenant", ["Login.Username"] = "Username", ["Login.Password"] = "Password",
                ["Login.TenantId"] = "Tenant ID", ["Login.Tagline"] = "Natural-language analytics — ask, analyze, and discover.",
                ["App.Subtitle"] = "AI Analytics Platform", ["Common.Settings"] = "Settings", ["Common.Logout"] = "Sign out",
                ["Common.Loading"] = "Loading…",
                ["Validation.Required"] = "This field is required.", ["Validation.Email"] = "Please enter a valid email address.", ["Validation.Format"] = "Invalid format.",
                ["Error.Generic"] = "An error occurred. Please try again later.", ["Error.NotFound"] = "The requested resource was not found.", ["Empty.NoData"] = "No data available.",
                ["Nav.Dashboard"] = "Dashboard", ["Nav.Ask"] = "Ask", ["Nav.DataSources"] = "Data Sources", ["Nav.Admin"] = "Admin",
                ["Accessibility.SkipToContent"] = "Skip to content", ["Theme.Light"] = "Light", ["Theme.Dark"] = "Dark",
            },
            ["ja-JP"] = new()
            {
                ["Common.Login"] = "ログイン", ["Common.Confirm"] = "確認", ["Common.Cancel"] = "キャンセル",
                ["Common.Save"] = "保存", ["Common.Close"] = "閉じる", ["Document.OutboundOrder"] = "出荷指示書",
                ["Login.Title"] = "ログイン / テナント選択", ["Login.Username"] = "ユーザー名", ["Login.Password"] = "パスワード",
                ["Login.TenantId"] = "テナントID", ["Login.Tagline"] = "自然言語で語る分析プラットフォーム —— 対話するだけで分析、見るだけで洞察。",
                ["App.Subtitle"] = "AI分析プラットフォーム", ["Common.Settings"] = "個人設定", ["Common.Logout"] = "ログアウト",
                ["Common.Loading"] = "読み込み中…",
                ["Validation.Required"] = "この項目は必須です。", ["Validation.Email"] = "有効なメールアドレスを入力してください。", ["Validation.Format"] = "形式が正しくありません。",
                ["Error.Generic"] = "エラーが発生しました。後でもう一度お試しください。", ["Error.NotFound"] = "要求されたリソースが見つかりません。", ["Empty.NoData"] = "データがありません。",
                ["Nav.Dashboard"] = "ダッシュボード", ["Nav.Ask"] = "質問", ["Nav.DataSources"] = "データソース", ["Nav.Admin"] = "管理",
                ["Accessibility.SkipToContent"] = "メインコンテンツへ", ["Theme.Light"] = "ライト", ["Theme.Dark"] = "ダーク",
            },
            ["ko-KR"] = new()
            {
                ["Common.Login"] = "로그인", ["Common.Confirm"] = "확인", ["Common.Cancel"] = "취소",
                ["Common.Save"] = "저장", ["Common.Close"] = "닫기", ["Document.OutboundOrder"] = "출고 주문",
                ["Login.Title"] = "로그인 / 테넌트 선택", ["Login.Username"] = "사용자 이름", ["Login.Password"] = "비밀번호",
                ["Login.TenantId"] = "테넌트 ID", ["Login.Tagline"] = "자연어 기반 지능형 분석 플랫폼 —— 대화가 곧 분석, 보는 것이 곧 인사이트.",
                ["App.Subtitle"] = "AI 분석 플랫폼", ["Common.Settings"] = "개인 설정", ["Common.Logout"] = "로그아웃",
                ["Common.Loading"] = "로딩 중…",
                ["Validation.Required"] = "이 항목은 필수입니다。", ["Validation.Email"] = "유효한 이메일 주소를 입력하세요。", ["Validation.Format"] = "형식이 올바르지 않습니다。",
                ["Error.Generic"] = "오류가 발생했습니다. 잠시 후 다시 시도하세요。", ["Error.NotFound"] = "요청한 리소스를 찾을 수 없습니다。", ["Empty.NoData"] = "데이터가 없습니다。",
                ["Nav.Dashboard"] = "대시보드", ["Nav.Ask"] = "질문", ["Nav.DataSources"] = "데이터 소스", ["Nav.Admin"] = "관리",
                ["Accessibility.SkipToContent"] = "주요 콘텐츠로 건너뛰기", ["Theme.Light"] = "라이트", ["Theme.Dark"] = "다크",
            },
        };

        // M3-05：键驱动种子。以 ResourceKeys.All() 为权威键集，保证新增键即时覆盖：
        // zh-CN 取内置 ZhCnDefaults（与 RCL Keys.Defaults 镜像一致），en-US 取 ResourceKeys.Catalog.DefaultValue；
        // zh-TW/ja-JP/ko-KR 优先保留手维护母语基线（defaults），缺失键回退到 en-US，避免错译且保证全覆盖。
        var enUs = ResourceKeys.Catalog.ToDictionary(kv => kv.Key, kv => kv.Value.DefaultValue ?? kv.Key);

        foreach (var locale in locales)
        {
            var existingKeys = await _db.UiTextResources
                .Where(x => x.TenantId == 0 && x.Culture == locale.Culture)
                .Select(x => x.ResourceKey).ToListAsync(ct);

            var toAdd = new List<UiTextResource>();
            foreach (var key in ResourceKeys.All())
            {
                if (existingKeys.Contains(key, StringComparer.OrdinalIgnoreCase)) continue;

                // 解析值：① 该文化手维护母语基线；② zh-CN 内置简体；③ en-US 基线；④ 兜底键名。
                string value;
                if (defaults.TryGetValue(locale.Culture, out var hand) && hand.TryGetValue(key, out var hv))
                    value = hv;
                else if (locale.Culture == "zh-CN" && ZhCnDefaults.TryGetValue(key, out var zv))
                    value = zv;
                else if (enUs.TryGetValue(key, out var ev))
                    value = ev;
                else
                    value = key;

                toAdd.Add(new UiTextResource
                {
                    TenantId = 0,
                    Culture = locale.Culture,
                    ResourceKey = key,
                    Value = value,
                    Description = key.StartsWith("Common.") ? "系统通用文本" : "系统界面文本",
                    IsTranslated = true,
                });
            }

            _db.UiTextResources.AddRange(toAdd);
        }

        await _db.SaveChangesAsync(ct);
    }

    /// <summary>
    /// 平台基线简体中文文案（zh-CN），与前端 RCL <c>Keys.Defaults</c> 的 ZhCn 镜像一致；后端单一事实来源。
    /// 公开以便回归测试断言「每个已登记键都有 zh-CN 基线」，避免新增键被静默降级为英文或键名。
    /// </summary>
    public static readonly Dictionary<string, string> ZhCnDefaults = new()
    {
        ["Common.Login"] = "登录", ["Common.Confirm"] = "确认", ["Common.Cancel"] = "取消",
        ["Common.Save"] = "保存", ["Common.Close"] = "关闭", ["Common.Settings"] = "个人设置",
        ["Common.Logout"] = "退出登录", ["Common.Loading"] = "加载中…", ["Common.Menu"] = "菜单",
        ["Common.Retry"] = "重试", ["Common.BackToWorkspace"] = "返回工作台", ["Common.CurrentUser"] = "当前用户",
        ["Common.Tenant"] = "租户", ["Common.User"] = "用户", ["Common.AccountMenu"] = "账号菜单",

        ["Login.Title"] = "登录 / 租户选择", ["Login.Username"] = "用户名", ["Login.Password"] = "口令",
        ["Login.TenantId"] = "租户 ID", ["Login.Tagline"] = "自然语言驱动的智能问数平台 —— 对话即分析，所见即洞察。",
        ["Login.InitEntryClosed"] = "初始化入口已关闭", ["Login.InitEntryClosedHint"] = "当前环境已禁用匿名初始化。请由部署配置完成首位平台管理员创建。",
        ["Login.InitPlatformAdmin"] = "初始化平台系统管理员", ["Login.InitNotice"] = "这是一次性初始化入口。创建完成后将永久关闭，请妥善保管管理员口令。",
        ["Login.AdminUsername"] = "管理员用户名", ["Login.DisplayName"] = "显示名", ["Login.AdminEmail"] = "管理员邮箱",
        ["Login.AdminPassword"] = "管理员口令", ["Login.ConfirmPassword"] = "确认口令", ["Login.CreateAdmin"] = "创建平台管理员",
        ["Login.TenantPlaceholder"] = "-- 请选择租户 --", ["Login.NoTenantRegister"] = "还没有租户？申请开通",
        ["Login.CheckingInit"] = "正在检查平台初始化状态…", ["Login.InitStatusError"] = "无法读取平台初始化状态。",
        ["Login.AdminUsernameRequired"] = "管理员用户名必填。", ["Login.AdminEmailInvalid"] = "请输入有效的管理员邮箱。",
        ["Login.AdminPasswordTooShort"] = "管理员口令至少 8 位。", ["Login.AdminPasswordMismatch"] = "两次输入的口令不一致。",
        ["Login.InitFailed"] = "平台管理员初始化失败。", ["Login.SelectTenantFirst"] = "请先选择租户。",
        ["Login.TenantCodePlaceholder"] = "如 demo / tenant-001", ["Login.TenantCodeHint"] = "租户目录未公开，请输入您已知的确切租户编码登录。",
        ["Login.TenantCodeInvalid"] = "租户编码不存在或已停用。",
        ["Login.TenantDirectoryLoadFailed"] = "租户列表加载失败，请检查 API 服务与地址配置。",
        ["Login.LoginFailed"] = "登录失败：用户不存在或已禁用。",
        ["Login.Hero.AINativeBI"] = "AI Native BI", ["Login.Hero.MultiTenant"] = "多租户", ["Login.Hero.Multilingual"] = "多语言",
        ["Login.Hero.LowCode"] = "低代码", ["Login.Hero.EnterpriseSaaS"] = "企业级 SaaS",

        ["App.Subtitle"] = "智能问数平台", ["Document.OutboundOrder"] = "出库单",

        ["Validation.Required"] = "此项为必填。", ["Validation.Email"] = "请输入有效的邮箱地址。", ["Validation.Format"] = "格式不正确。",

        ["Error.Generic"] = "发生错误，请稍后重试。", ["Error.NotFound"] = "未找到请求的资源。", ["Error.Unauthorized"] = "未授权。",
        ["Error.Forbidden"] = "无权访问该资源。", ["Error.Validation"] = "输入校验未通过。", ["Error.Conflict"] = "操作冲突，请刷新后重试。",
        ["Error.RateLimited"] = "请求过于频繁，请稍后再试。", ["Error.Maintenance"] = "系统维护中，请稍后访问。",
        ["Error.PageRender"] = "页面渲染出错", ["Error.PageRenderDesc"] = "该页面在渲染时发生异常，已被安全隔离，未影响其它功能。可重试当前页面或返回工作台。",
        ["Error.TechDetails"] = "技术详情",
        ["Error.Localization.CultureInvalid"] = "文化格式无效。", ["Error.Localization.TextEmpty"] = "文本不能为空。",
        ["Error.Localization.PlaceholderMismatch"] = "译文占位符与平台基线不一致。", ["Error.Localization.BaselineReset"] = "平台基线不能使用重置覆盖操作。",
        ["Error.OperationFailed"] = "操作失败。", ["Error.CodeLabel"] = "错误码：", ["Error.TraceIdLabel"] = "追踪 ID：",

        // M3-05 递延项：后端统一错误码 zh-CN 基线（与 Api/Errors/ErrorCodes.cs 的 Friendly 中文文案完全一致）。
        ["Error.SB_BAD_REQUEST"] = "请求参数不合法，请检查输入后重试。",
        ["Error.SB_UNAUTHORIZED"] = "鉴权失败，请重新登录后再试。",
        ["Error.SB_FORBIDDEN"] = "权限不足，当前账号无权执行该操作。",
        ["Error.SB_NOT_FOUND"] = "请求的资源不存在或已被删除。",
        ["Error.SB_UNSUPPORTED"] = "当前操作不被支持。",
        ["Error.SB_INTERNAL"] = "服务暂时不可用，请稍后重试；如持续出现，可凭错误码联系管理员。",
        ["Error.SB_SERVICE_UNAVAILABLE"] = "平台尚未就绪（数据库不可达或尚未完成初始化），请稍后重试或联系管理员。",
        ["Error.SB_TOO_MANY_REQUESTS"] = "请求过于频繁，请稍后再试。",
        ["Error.SB_AUTH_001"] = "用户名或租户不存在，或账号已被禁用。",
        ["Error.SB_BI_001"] = "未能从问题中识别出可查询的数据表，请换一种表述或指定具体业务对象（如「订单」「库存」）。",
        ["Error.SB_BI_002"] = "未能从问题中识别可分析的字段，请补充指标或维度（如「销售额」「按地区」）。",
        ["Error.SB_BI_003"] = "当前业务语义暂不支持该分析（如聚合方式不受支持），请调整问法。",
        ["Error.SB_BI_004"] = "问题中存在多个可能匹配的度量字段，请明确指定（如「订单金额」而非「金额」）。",
        ["Error.SB_BI_005"] = "模型对该查询的把握不足，请补充更明确的指标、维度或筛选条件后重试。",
        ["Error.SB_BI_006"] = "数据源暂时不可达，请稍后重试或联系管理员检查连接。",
        ["Error.SB_APP_001"] = "应用定义（DSL）不合法，请检查组件配置后重试。",
        ["Error.SB_AGENT_001"] = "智能体未返回有效内容，请重新描述任务。",
        ["Error.SB_PFM_001"] = "当前租户配额已用尽，请升级套餐或联系管理员。",
        ["Error.SB_PFM_002"] = "操作越过了租户边界，已被安全策略拒绝。",
        ["Error.SB_AUTHZ_001"] = "当前账号无权访问所选数据源。",
        ["Error.SB_AUTHZ_002"] = "当前账号没有满足行级数据策略的访问范围。",
        ["Error.SB_SECURITY_001"] = "查询计划未通过最终安全校验，已在执行前阻断。",

        ["Page.Title.Home"] = "工作台", ["Page.Desc.Home"] = "从一次提问开始，把分析沉淀为仪表盘与应用，并在团队内复用。", ["Page.Title.Profile"] = "个人设置", ["Page.Desc.Profile"] = "查看账号与租户信息，调整界面偏好。", ["Page.Title.Tenants"] = "租户管理",
        ["Page.Title.TenantMembers"] = "租户成员", ["Page.Title.Identity"] = "身份与权限", ["Page.Title.Quota"] = "配额管理",
        ["Page.Title.PlatformAdmins"] = "平台管理员", ["Page.Title.PlatformAdminScopes"] = "管理员租户范围",
        ["Page.Title.SelfRegistrationAdmin"] = "自助注册", ["Page.Title.SystemStatus"] = "系统状态",
        ["Page.Title.Localization"] = "多语言中心", ["Page.Title.Themes"] = "主题（租户级）", ["Page.Title.DemoData"] = "演示数据",
        ["Page.Title.BusinessModel"] = "语义模型", ["Page.Title.BusinessModelEntityDetail"] = "实体详情",
        ["Page.Title.SemanticLabelDetail"] = "语义标签详情", ["Page.Title.ComponentGallery"] = "组件库",
        ["Page.Title.ThemeEditor"] = "主题编辑器", ["Page.Title.DataSources"] = "数据源管理",
        ["Page.Title.ModelAccounts"] = "模型与账号（BYO）", ["Page.Title.MetadataEntityDetail"] = "元数据关系详情",
        ["Page.Title.DataSource"] = "数据源详情",

        ["Page.Desc.BusinessModel"] = "把物理表结构映射为业务语言：实体、业务域与字段同义词，让自然语言问数更精准。",
        ["Page.Desc.BusinessModelEntityDetail"] = "查看实体映射、字段口径与解析状态。",
        ["Page.Desc.SemanticLabelDetail"] = "查看标签口径、同义词与召回策略。",
        ["Page.Desc.ComponentGallery"] = "以安全的结构化 DSL 创建、发布和复用租户组件。",
        ["Page.Desc.ThemeEditor"] = "基于古风色板自定义你的视觉风格：实时预览、保存并指派给租户或复制为蓝图。",
        ["Page.Desc.DataSources"] = "统一管理租户数据连接、元数据覆盖与访问状态。",
        ["Page.Desc.ModelAccounts"] = "选择当前 AI 模型，或绑定你自有的模型 API Key（BYO），按租户隔离、密钥掩码存储。",
        ["Page.Desc.MetadataEntityDetail"] = "查看元数据实体的实际数据、所属对象及向量索引关系。",
        ["Page.Desc.DataSource"] = "数据源的授权清单与行级安全策略（RLS）。",

        ["Empty.NoData"] = "暂无数据。",

        ["Action.New"] = "新建", ["Action.Create"] = "创建", ["Action.Save"] = "保存", ["Action.Cancel"] = "取消",
        ["Action.Refresh"] = "刷新", ["Action.Delete"] = "删除", ["Action.Edit"] = "编辑",         ["Action.Search"] = "搜索", ["Action.Close"] = "关闭", ["Action.Reset"] = "重置", ["Action.ThemeAssignDefault"] = "指派为默认",

        ["Page.ThemeEditor.Preview"] = "实时预览", ["Page.ThemeEditor.Palette"] = "调色板",

        ["Nav.Home"] = "首页", ["Nav.Ask"] = "Ask BI 智能问数", ["Nav.Dashboards"] = "仪表盘", ["Nav.Apps"] = "应用工厂",
        ["Nav.Agent"] = "智能体 / Copilot", ["Nav.SemanticLabels"] = "语义标签", ["Nav.BusinessModel"] = "语义模型",
        ["Nav.Components"] = "组件库", ["Nav.ThemeEditor"] = "主题编辑器", ["Nav.DataSources"] = "数据源",
        // 历史别名：与 RCL 镜像、后端 Catalog 保持一致（护栏测试 All_RegisteredKeys_HaveZhCnBaseline 会校验）。
        ["Nav.Dashboard"] = "仪表盘", ["Nav.Admin"] = "管理",
        ["Nav.ModelAccounts"] = "模型与账号", ["Nav.Tenants"] = "租户", ["Nav.TenantMembers"] = "租户成员",
        ["Nav.SelfRegistration"] = "自助注册", ["Nav.DemoData"] = "演示数据", ["Nav.PlatformAdmins"] = "平台管理员",
        ["Nav.PlatformAdminScopes"] = "管理员租户范围", ["Nav.Identity"] = "身份权限", ["Nav.Audit"] = "审计",
        ["Nav.Quota"] = "配额", ["Nav.Localization"] = "多语言", ["Nav.Themes"] = "主题", ["Nav.System"] = "系统状态",
        ["Nav.Group.Flagship"] = "旗舰", ["Nav.Group.Analysis"] = "分析", ["Nav.Group.Custom"] = "自定义",
        ["Nav.Group.PlatformExt"] = "平台扩展", ["Nav.Group.Admin"] = "管理后台",

        ["Accessibility.SkipToContent"] = "跳到主内容",
        ["Theme.Light"] = "浅色", ["Theme.Dark"] = "深色", ["Theme.Switch"] = "切换主题",

        // M3-05 重内容页正文批次：Content.* 简体基线
        ["Content.BusinessModelDomains"] = "业务域", ["Content.BusinessModelDomainsSub"] = "用于分类",
        ["Content.BusinessModelEntities"] = "实体", ["Content.BusinessModelEntitiesSub"] = "对应业务表",
        ["Content.BusinessModelResolved"] = "已解析语义", ["Content.BusinessModelResolvedSub"] = "可在 Ask 提问",
        ["Content.BusinessModelSearchPlaceholder"] = "搜索实体…",
        ["Content.BusinessModelEmptyDomainsTitle"] = "暂无业务域",
        ["Content.BusinessModelEmptyDomainsText"] = "业务域用于组织对实体的分类，例如「销售」「库存」「财务」。",
        ["Content.BusinessModelEmptyEntitiesTitle"] = "暂无实体",
        ["Content.BusinessModelEmptyEntitiesText"] = "实体对应一张业务表（如「客户」「订单」），解析后可在 Ask 中直接以业务名提问。",
        ["Content.BusinessModelNoMatch"] = "无匹配实体",
        ["Content.BusinessModelDetail"] = "详情",
        ["Content.BusinessModelEditorNotReady"] = "实体编辑器将在 S2 阶段接入。",

        ["Content.BusinessModelEntityLoading"] = "正在加载实体详情…",
        ["Content.BusinessModelEntityPanelDetail"] = "详情",
        ["Content.BusinessModelEntityEmptyTitle"] = "未找到该实体",
        ["Content.BusinessModelEntityEmptyText"] = "实体可能已被删除，或后端详情端点尚未接入。",
        ["Content.BusinessModelEntityPanelInfo"] = "实体信息",
        ["Content.BusinessModelEntityBack"] = "返回语义模型",
        ["Content.BusinessModelStatusActive"] = "已激活", ["Content.BusinessModelStatusDraft"] = "草稿",
        ["Content.BusinessModelStatusUnresolved"] = "未解析", ["Content.BusinessModelStatusDeprecated"] = "已弃用",
        ["Content.BusinessModelDeleteConfirm"] = "确定要删除该实体吗？此操作不可撤销，仅删除实体级元数据（子聚合的编辑留待后续里程碑）。",

        ["Content.DataSourcesNew"] = "新增数据源",
        ["Content.DataSourcesMetricTotal"] = "数据源总数", ["Content.DataSourcesMetricOnline"] = "在线连接",
        ["Content.DataSourcesMetricTables"] = "元数据表", ["Content.DataSourcesMetricColumns"] = "已识别字段",
        ["Content.DataSourcesPanelAssets"] = "连接资产",
        ["Content.DataSourcesSearchPlaceholder"] = "搜索名称或数据库类型…",
        ["Content.DataSourcesLoading"] = "正在加载数据源…",
        ["Content.DataSourcesEmptyTitle"] = "暂无数据源",
        ["Content.DataSourcesEmptyText"] = "请在下方创建第一个数据源。",
        ["Content.DataSourcesColId"] = "ID", ["Content.DataSourcesColName"] = "名称", ["Content.DataSourcesColType"] = "类型",
        ["Content.DataSourcesColStatus"] = "状态", ["Content.DataSourcesColTables"] = "元数据表", ["Content.DataSourcesColColumns"] = "字段",
        ["Content.DataSourcesTenantScoped"] = "租户专属连接",
        ["Content.DataSourcesStatusOnline"] = "运行中", ["Content.DataSourcesStatusOffline"] = "已停用",
        ["Content.DataSourcesManage"] = "管理连接 →",
        ["Content.DataSourcesModalTitle"] = "接入新的数据源",
        ["Content.DataSourcesConnSqlServer"] = "企业主流关系型数据库", ["Content.DataSourcesConnMysql"] = "WMS 等业务常用",
        ["Content.DataSourcesConnPostgres"] = "开源关系型数据库", ["Content.DataSourcesConnOracle"] = "大型事务系统",
        ["Content.DataSourcesConnClickhouse"] = "列式分析型数据库", ["Content.DataSourcesConnMongodb"] = "文档型 NoSQL",
        ["Content.DataSourcesFieldName"] = "数据源名称", ["Content.DataSourcesFieldNameHint"] = "给团队一个易识别的名称",
        ["Content.DataSourcesFieldNamePlaceholder"] = "如：WMS 生产库", ["Content.DataSourcesFieldType"] = "连接器类型",
        ["Content.DataSourcesFieldConnStr"] = "连接串", ["Content.DataSourcesFieldConnStrPlaceholder"] = "Server=host;Database=db;User=...;",
        ["Content.DataSourcesTestConn"] = "测试连接", ["Content.DataSourcesSaveAndConnect"] = "保存并接入",
        ["Content.DataSourcesLoadFailed"] = "加载数据源失败。",
        ["Content.DataSourcesConnectorSelected"] = "已选择连接器：{0}",
        ["Content.DataSourcesTestSubmitted"] = "连通性测试已提交（Multi-DB Connector 后端计划于 P12 实现）。",
        ["Content.DataSourcesRequiredError"] = "数据源名称和连接串必填。",
        ["Content.DataSourcesColConnStatus"] = "连接状态", ["Content.DataSourcesColLastScan"] = "最后扫描",
        ["Content.DataSourcesConnOk"] = "已连通", ["Content.DataSourcesConnFailed"] = "连接失败",
        ["Content.DataSourcesConnUnknown"] = "未测试", ["Content.DataSourcesConnNever"] = "从未扫描",
        ["Content.DataSourcesEnable"] = "启用", ["Content.DataSourcesDisable"] = "停用",
        ["Content.DataSourcesTesting"] = "测试中…",
        ["Content.DataSourcesEditTitle"] = "编辑数据源", ["Content.DataSourcesEditConnStr"] = "重置连接串",
        ["Content.DataSourcesEditConnStrPlaceholder"] = "输入新连接串以重置（原值不回显）",
        ["Content.DataSourcesEditResetNote"] = "连接串仅可重置，原值不会回显。",
        ["Content.DataSourcesTestedToast"] = "连接测试：{0}", ["Content.DataSourcesToggledToast"] = "数据源已{0}",
        ["Content.DataSourcesEditSavedToast"] = "数据源已保存。", ["Content.DataSourcesEditFailed"] = "保存失败。",
        ["Content.DataSourcesSaveFailed"] = "保存数据源失败。",
        ["Content.DataSourcesSavedToast"] = "数据源已保存，并已授权给当前管理员。Ask 页面现在可以选择它。",
        ["Content.DataSourcesSaving"] = "正在保存…",

        ["Content.DataSourceBackList"] = "返回列表",
        ["Content.DataSourceTabMeta"] = "元数据", ["Content.DataSourceRescan"] = "重新扫描", ["Content.DataSourceScanning"] = "扫描中…",
        ["Content.DataSourceLoadingMeta"] = "正在加载元数据…",
        ["Content.DataSourceEmptyMetaTitle"] = "尚未扫描到元数据",
        ["Content.DataSourceEmptyMetaText"] = "点击重新扫描，从业务数据库读取表和字段结构。",
        ["Content.DataSourceScanQueued"] = "已排队，等待后台扫描…",
        ["Content.DataSourceScanRunning"] = "正在扫描元数据…",
        ["Content.DataSourceScanProgressLabel"] = "扫描进度",
        ["Content.DataSourceScanTablesScanned"] = "已扫描表：{0}",
        ["Content.DataSourceScanColumnsScanned"] = "已扫描字段：{0}",
        ["Content.DataSourceScanOrphansRemoved"] = "已清理孤儿对象：{0}",
        ["Content.DataSourceScanSucceededBanner"] = "扫描完成",
        ["Content.DataSourceScanFailedBanner"] = "扫描失败",
        ["Content.DataSourceScanJobLost"] = "扫描任务不存在或已被清理。",
        ["Content.DataSourceScanRetry"] = "重试",
        ["Content.DataSourceEmptyMetaNextStep"] = "可先测试数据源连接、授予访问授权，再重新扫描。",
        ["Content.DataSourceScanPollingError"] = "轮询扫描状态失败：{0}",
        ["Content.DataSourceFieldsBadge"] = "{0} 字段",
        ["Content.DataSourceColFieldRel"] = "字段 / 关系", ["Content.DataSourceColType"] = "类型",
        ["Content.DataSourceColNullable"] = "可空", ["Content.DataSourceColSemantic"] = "Semantic",
        ["Content.DataSourceColVector"] = "Vector", ["Content.DataSourceColBusinessKey"] = "业务键",
        ["Content.DataSourceNotVectorized"] = "未向量化",
        ["Content.DataSourceTabGrants"] = "访问授权", ["Content.DataSourceGrantUser"] = "用户", ["Content.DataSourceGrantRole"] = "角色",
        ["Content.DataSourceGrantSubjectPlaceholder"] = "选择授权主体…", ["Content.DataSourceGrantAccess"] = "授予访问",
        ["Content.DataSourceRefreshGrants"] = "刷新授权", ["Content.DataSourceLoadingGrants"] = "正在加载授权…",
        ["Content.DataSourceEmptyGrantsTitle"] = "暂无显式授权",
        ["Content.DataSourceEmptyGrantsText"] = "选择用户或角色并授予该数据源访问权限。",
        ["Content.DataSourcePanelGrants"] = "授权清单",
        ["Content.DataSourceColSubjectType"] = "主体类型", ["Content.DataSourceColSubject"] = "主体",
        ["Content.DataSourceColCreated"] = "授权时间", ["Content.DataSourceColActions"] = "操作", ["Content.DataSourceRevoke"] = "撤销",
        ["Content.DataSourceTabRls"] = "行级安全", ["Content.DataSourceLoadingPolicies"] = "正在加载策略…",
        ["Content.DataSourcePanelRls"] = "行级安全策略",
        ["Content.DataSourceEmptyRlsTitle"] = "未配置行级安全策略",
        ["Content.DataSourceEmptyRlsText"] = "配置后可按用户/角色限制可见数据行，控制越权取数风险。",
        ["Content.DataSourcePanelPolicies"] = "策略清单",
        ["Content.DataSourceLoadMetaFailed"] = "加载元数据失败（{0}）。",
        ["Content.DataSourceScanFailed"] = "元数据扫描失败。", ["Content.DataSourceScanDone"] = "元数据扫描完成。",
        ["Content.DataSourceSelectSubject"] = "请选择用户或角色。",
        ["Content.DataSourceGrantFailed"] = "授权失败。", ["Content.DataSourceGranted"] = "数据源访问权限已授予。",
        ["Content.DataSourceRevokeFailed"] = "撤销失败。", ["Content.DataSourceRevoked"] = "授权已撤销。",
        ["Content.DataSourceLoadPolicyFailed"] = "加载策略失败（{0}）。",
        ["Content.DataSourcePolicyDeleted"] = "策略已删除。", ["Content.DataSourceDeleteFailed"] = "删除失败（{0}）。",
        ["Content.DataSourceLoadGrantsFailed"] = "加载授权失败（{0}）。",

        // M3-05 重内容页正文批次（续）：ModelAccounts / SemanticLabel / ComponentGallery / ThemeEditor 补充 / MetadataEntity
        ["Content.ModelAccountsBound"] = "已绑定", ["Content.ModelAccountsUnbound"] = "未绑定",
        ["Content.ModelAccountsDefault"] = "默认", ["Content.ModelAccountsSetDefault"] = "设为默认",
        ["Content.ModelAccountsBindPanel"] = "绑定自有 API Key", ["Content.ModelAccountsFieldModel"] = "模型",
        ["Content.ModelAccountsFieldApiKey"] = "API Key", ["Content.ModelAccountsApiKeyPlaceholder"] = "sk-••••••",
        ["Content.ModelAccountsFieldNote"] = "备注", ["Content.ModelAccountsNotePlaceholder"] = "如：生产环境专用",
        ["Content.ModelAccountsSaveBind"] = "保存绑定", ["Content.ModelAccountsSetDefaultToast"] = "已将 {0} 设为默认模型",
        ["Content.ModelAccountsBindSubmitted"] = "绑定已保存。",
        ["Content.ModelAccountsDeleted"] = "已删除绑定。",
        ["Content.ModelAccountsDeleteConfirm"] = "确认删除该模型绑定？密钥将从库中移除。",
        ["Content.ModelAccountsBindFailed"] = "绑定失败：{0}",

        ["Content.SemanticLabelLoading"] = "正在加载标签详情…",
        ["Content.SemanticLabelPanelDetail"] = "详情",
        ["Content.SemanticLabelNotFoundTitle"] = "未找到该标签",
        ["Content.SemanticLabelNotFoundText"] = "标签可能已被删除，或后端详情端点尚未接入。",
        ["Content.SemanticLabelInfoPanel"] = "标签信息",
        ["Content.SemanticLabelBack"] = "返回列表",

        ["Content.ComponentGallerySecButtons"] = "按钮", ["Content.ComponentGallerySecBadges"] = "徽标",
        ["Content.ComponentGallerySecForms"] = "表单控件", ["Content.ComponentGallerySecProgress"] = "进度条",
        ["Content.ComponentGallerySecSegmented"] = "分段控件", ["Content.ComponentGallerySecAlerts"] = "告警",
        ["Content.ComponentGallerySecTabs"] = "标签页 SbTabs", ["Content.ComponentGallerySecDataTable"] = "数据表格 SbDataTable",
        ["Content.ComponentGallerySecModal"] = "弹窗 SbModal / SbConfirm", ["Content.ComponentGallerySecToast"] = "轻提示 Toast",
        ["Content.ComponentGallerySecGuard"] = "守卫 Guard",
        ["Content.ComponentGalleryBtnPrimary"] = "主要", ["Content.ComponentGalleryBtnSecondary"] = "次要",
        ["Content.ComponentGalleryBtnGhost"] = "幽灵", ["Content.ComponentGalleryBtnDanger"] = "危险", ["Content.ComponentGalleryBtnDisabled"] = "禁用",
        ["Content.ComponentGalleryBadgePrimary"] = "主要", ["Content.ComponentGalleryBadgePublished"] = "已发布",
        ["Content.ComponentGalleryBadgeDraft"] = "草稿", ["Content.ComponentGalleryBadgeFailed"] = "失败",
        ["Content.ComponentGalleryBadgeGlobal"] = "全局", ["Content.ComponentGalleryBadgeDefault"] = "默认",
        ["Content.ComponentGalleryFormTextbox"] = "文本框", ["Content.ComponentGalleryFormDropdown"] = "下拉",
        ["Content.ComponentGalleryOptA"] = "选项 A", ["Content.ComponentGalleryOptB"] = "选项 B",
        ["Content.ComponentGalleryProgressUsed"] = "已用 {0}",
        ["Content.ComponentGallerySegDay"] = "日", ["Content.ComponentGallerySegWeek"] = "周", ["Content.ComponentGallerySegMonth"] = "月",
        ["Content.ComponentGalleryAlertInfo"] = "信息提示", ["Content.ComponentGalleryAlertWarning"] = "注意提示",
        ["Content.ComponentGalleryStatQuestions"] = "今日问数", ["Content.ComponentGalleryStatHitRate"] = "命中率",
        ["Content.ComponentGalleryStatPending"] = "待复核", ["Content.ComponentGalleryStatActiveTenants"] = "活跃租户",
        ["Content.ComponentGallerySampleTable"] = "示例表格",
        ["Content.ComponentGalleryColCode"] = "编码", ["Content.ComponentGalleryColName"] = "名称",
        ["Content.ComponentGalleryColStatus"] = "状态", ["Content.ComponentGalleryColTenant"] = "租户",
        ["Content.ComponentGalleryDemoSales"] = "销售看板", ["Content.ComponentGalleryDemoStock"] = "库存预警",
        ["Content.ComponentGalleryDemoFinance"] = "财务月报",
        ["Content.ComponentGalleryCardAskTitle"] = "Ask BI", ["Content.ComponentGalleryCardAskDesc"] = "自然语言问数的旗舰入口。",
        ["Content.ComponentGalleryCardDashTitle"] = "仪表盘", ["Content.ComponentGalleryCardDashDesc"] = "固化可复用的可视化看板。",
        ["Content.ComponentGalleryCardAppTitle"] = "应用工厂", ["Content.ComponentGalleryCardAppDesc"] = "把会话沉淀为 BI 应用。",
        ["Content.ComponentGalleryTabOverview"] = "概览", ["Content.ComponentGalleryTabDetail"] = "明细", ["Content.ComponentGalleryTabSettings"] = "设置",
        ["Content.ComponentGalleryDataEmpty"] = "无数据",
        ["Content.ComponentGalleryModalTitle"] = "示例弹窗", ["Content.ComponentGalleryOpenModal"] = "打开弹窗", ["Content.ComponentGalleryModalBody"] = "弹窗用于承载表单或详情，支持遮罩点击关闭与自定义底部操作。",
        ["Content.ComponentGalleryModalOk"] = "知道了",
        ["Content.ComponentGalleryConfirmTitle"] = "删除确认", ["Content.ComponentGalleryConfirmMsg"] = "此操作不可撤销，确定要删除该记录吗？",
        ["Content.ComponentGalleryConfirmText"] = "删除",
        ["Content.ComponentGalleryToastInfo"] = "信息提示", ["Content.ComponentGalleryToastSuccess"] = "操作成功",
        ["Content.ComponentGalleryToastWarning"] = "请注意", ["Content.ComponentGalleryToastError"] = "出错了",
        ["Content.ComponentGalleryToastDeleted"] = "已确认删除（演示）。",
        ["Content.ComponentGalleryGuardDesc"] = "AuthGuard 等待会话自举完成后渲染子内容；PermissionGuard 按权限码门控（当前未强制，见 NavMenuItems.EnforcePermissions）。",
        ["Content.ComponentGalleryGuardHasPerm"] = "你拥有 demo:write 权限",
        ["Content.ComponentLibraryAssets"] = "组件资产",
        ["Content.ComponentLibraryLifecycleHint"] = "草稿与发布态隔离；回滚会创建新版本，不覆盖历史。",
        ["Content.ComponentLibraryNew"] = "新增组件",
        ["Content.ComponentLibraryEmptyTitle"] = "暂无自定义组件",
        ["Content.ComponentLibraryEmptyText"] = "创建第一个组件，发布后即可被应用和仪表盘安全复用。",
        ["Content.ComponentLibraryType"] = "类型",
        ["Content.ComponentLibraryVersion"] = "发布版本",
        ["Content.ComponentLibraryPublishedAt"] = "发布时间",
        ["Content.ComponentLibraryActions"] = "操作",
        ["Content.ComponentLibraryPreview"] = "预览",
        ["Content.ComponentLibraryVersions"] = "版本",
        ["Content.ComponentLibraryPublish"] = "发布",
        ["Content.ComponentLibraryEditTitle"] = "编辑组件",
        ["Content.ComponentLibraryKey"] = "组件键",
        ["Content.ComponentLibraryKeyHint"] = "小写字母开头，仅允许小写字母、数字和连字符；创建后不可修改。",
        ["Content.ComponentLibraryDescription"] = "描述",
        ["Content.ComponentLibraryDsl"] = "结构化 DSL",
        ["Content.ComponentLibraryDslHint"] = "仅支持白名单结构，不接受 HTML、CSS 或 JavaScript。",
        ["Content.ComponentLibrarySaving"] = "保存中…",
        ["Content.ComponentLibraryPreviewTitle"] = "已发布组件预览",
        ["Content.ComponentLibraryVersionHistory"] = "发布版本历史",
        ["Content.ComponentLibraryNoVersions"] = "该组件尚未发布。",
        ["Content.ComponentLibraryCurrent"] = "当前",
        ["Content.ComponentLibraryRollback"] = "回滚至此版本",
        ["Content.ComponentLibraryDeleteConfirm"] = "删除组件将同时删除其全部版本，确定继续吗？",
        ["Content.ComponentLibraryLoadFailed"] = "组件加载失败。",
        ["Content.ComponentLibraryInvalidForm"] = "请填写名称，并使用合法的组件键。",
        ["Content.ComponentLibraryInvalidDsl"] = "DSL 无效：{0}",
        ["Content.ComponentLibrarySaveFailed"] = "组件保存失败。",
        ["Content.ComponentLibrarySaved"] = "组件已保存。",
        ["Content.ComponentLibraryPublishFailed"] = "组件发布失败。",
        ["Content.ComponentLibraryPublished"] = "组件已发布。",
        ["Content.ComponentLibraryUnpublished"] = "组件尚未发布，暂无运行时预览。",
        ["Content.ComponentLibraryRollbackFailed"] = "组件回滚失败。",
        ["Content.ComponentLibraryRollbackDone"] = "已回滚并生成新的发布版本。",
        ["Content.ComponentLibraryDeleteFailed"] = "组件删除失败。",
        ["Content.ComponentLibraryDeleted"] = "组件已删除。",

        ["Content.ThemeEditorSampleMetric"] = "示例指标", ["Content.ThemeEditorBtnPrimary"] = "主要按钮",
        ["Content.ThemeEditorBtnSecondary"] = "次要", ["Content.ThemeEditorBadgePublished"] = "已发布",
        ["Content.ThemeEditorBadgeDraft"] = "草稿", ["Content.ThemeEditorSavedToast"] = "主题已保存。", ["Content.ThemeEditorSelectTheme"] = "选择主题", ["Content.ThemeEditorNew"] = "新建主题", ["Content.ThemeEditorSaved"] = "主题已保存。", ["Content.ThemeEditorSaveFailed"] = "保存失败：{0}", ["Content.ThemeEditorKey"] = "主题键", ["Content.ThemeEditorName"] = "主题名称", ["Content.ThemeEditorKeyInvalid"] = "主题键仅允许小写字母、数字和连字符（-）。", ["Content.ThemeEditorDeleteConfirm"] = "确定要删除该主题吗？此操作不可撤销。", ["Content.ThemeEditorAssigned"] = "已指派为租户默认主题。",

        ["Content.MetadataEntityLoading"] = "正在读取元数据实体…",
        ["Content.MetadataEntityIntro"] = "以下内容来自当前租户的实际元数据记录。",
        ["Content.MetadataEntityNotFound"] = "未找到对应数据（{0}）。",
        // M3-05 递延项（Task #83）：分析页正文键 zh-CN 基线
        ["Content.AskTitle"] = "Ask BI 智能问数（旗舰）",
        ["Content.AskRestoringSession"] = "正在恢复登录会话…",
        ["Content.AskLoginHint"] = "请先",
        ["Content.AskLoginLink"] = "登录",
        ["Content.AskLoginHint2"] = "后再问数。",
        ["Content.AskDataScope"] = "可访问数据范围",
        ["Content.AskDataLoading"] = "加载中…",
        ["Content.AskQuestionLabel"] = "自然语言问题",
        ["Content.AskQuestionPlaceholder"] = "例如：上个月各区域销售额对比",
        ["Content.AskButtonAsk"] = "提问",
        ["Content.AskButtonClear"] = "清空对话",
        ["Content.AskHistoryRestored"] = "已恢复 {0} 轮历史",
        ["Content.AskNoConversation"] = "还没有对话。试着问一个业务问题，例如「本月各品类销售额 Top 10」。",
        ["Content.AskDataSourceListEmpty"] = "数据源列表为空",
        ["Content.AskNoDataSources"] = "当前账号暂无可用数据源",
        ["Content.AskDataSourceLoadFailed"] = "数据源加载失败：{0}",
        ["Content.AskEnterQuestion"] = "请输入问题。",
        ["Content.AskNoAuthorizedDataSource"] = "当前账号尚未获授权任何数据源，请联系租户管理员。",
        ["Content.AskEnterRefineInstruction"] = "请输入细化指令。",
        ["Content.AskRefineBasedOnResult"] = "已基于本轮结果重新查询（多轮语义调整）。",
        ["Content.AskRefineException"] = "细化异常：{0}",
        ["Content.AskFailed"] = "问数失败。",
        ["Content.AskNoValidResult"] = "问数未返回有效结果。",
        ["Content.AskPublishedAppNamePrefix"] = "问数应用：",
        ["Content.AskChartTitleDefault"] = "结果图",
        ["Content.AskTableTitleDefault"] = "明细数据",
        ["Content.AskAiSummaryTitle"] = "AI 解读",
        ["Content.AskPublishSuccess"] = "已发布为应用：{0}",
        ["Content.AskPublishFailed"] = "发布失败：{0}",
        ["Content.AskPublishException"] = "发布异常：{0}",
        ["Content.DashboardsTitle"] = "仪表盘",
        ["Content.DashboardsDesc"] = "将 Ask 分析结果固化为可复用的可视化看板，支持团队共享与定时刷新。",
        ["Content.DashboardsSearchPlaceholder"] = "搜索名称 / 编码…",
        ["Content.DashboardsEmptyTitle"] = "暂无仪表盘",
        ["Content.DashboardsEmptyText"] = "将一次问数结果保存为仪表盘，即可在团队内复用这套分析视角与图表。",
        ["Content.DashboardsLoading"] = "正在加载仪表盘…",
        ["Content.DashboardsNew"] = "新建仪表盘",
        ["Content.DashboardsStatTotal"] = "仪表盘总数",
        ["Content.DashboardsStatTotalSub"] = "含全局模板",
        ["Content.DashboardsStatPublished"] = "已发布",
        ["Content.DashboardsStatPublishedSub"] = "可对外共享",
        ["Content.DashboardsStatDraft"] = "草稿",
        ["Content.DashboardsStatDraftSub"] = "编辑中",
        ["Content.DashboardsPublishFromAsk"] = "从 Ask 发布",
        ["Content.DashboardsRowDetail"] = "详情",
        ["Content.DashboardsRowDelete"] = "删除",
        ["Content.DashboardsDeleteConfirmMsg"] = "删除后不可恢复，确认要删除该仪表盘吗？",
        ["Content.DashboardsDeleteConfirmText"] = "删除",
        ["Content.DashboardsFieldStatus"] = "状态",
        ["Content.DashboardsStatusDraft"] = "草稿",
        ["Content.DashboardsStatusPublished"] = "已发布",
        ["Content.DashboardsFieldDslJson"] = "DslJson",
        ["Content.DashboardsFieldDslJsonHint"] = "声明式仪表盘定义（DashboardDsl JSON）。保存将校验后创建。",
        ["Content.DashboardsModalCancel"] = "取消",
        ["Content.DashboardsModalCreate"] = "创建",
        ["Content.DashboardsMissingIdOpen"] = "该记录缺少 id，无法打开详情。",
        ["Content.DashboardsMissingIdDelete"] = "该记录缺少 id，无法删除。",
        ["Content.DashboardsDeleteSuccess"] = "仪表盘已删除。",
        ["Content.DashboardsDeleteFailed"] = "删除失败。",
        ["Content.DashboardsBlueprintUnavailable"] = "未能获取蓝图骨架，请手动填写 DslJson。",
        ["Content.DashboardsDslJsonEmpty"] = "DslJson 不能为空。",
        ["Content.DashboardsCreateSuccess"] = "仪表盘已创建。",
        ["Content.DashboardsCreateFailed"] = "创建失败（HTTP {0}）。",
        ["Content.DashboardsLoadFailed"] = "加载失败。",
        ["Content.AppsTitle"] = "应用工厂",
        ["Content.AppsDesc"] = "将问数会话沉淀为可复用的 BI 应用：可视化编辑器、DSL 蓝图与一键发布。",
        ["Content.AppsSearchPlaceholder"] = "搜索应用编码 / 名称…",
        ["Content.AppsEmptyTitle"] = "还没有应用",
        ["Content.AppsEmptyText"] = "应用是问数能力的封装：把一次典型分析固化为卡片、图表与筛选器，分享给团队即可复用。",
        ["Content.AppsLoading"] = "正在加载应用…",
        ["Content.AppsPanelTitle"] = "应用清单",
        ["Content.AppsNew"] = "新建应用",
        ["Content.AppsFromAsk"] = "从 Ask 发布",
        ["Content.AppsStatTotal"] = "应用总数",
        ["Content.AppsStatTotalSub"] = "含全局模板",
        ["Content.AppsStatGlobal"] = "全局模板",
        ["Content.AppsStatGlobalSub"] = "平台内置",
        ["Content.AppsStatTenant"] = "租户应用",
        ["Content.AppsStatTenantSub"] = "本租户自建",
        ["Content.AppsNoDescription"] = "（暂无描述）",
        ["Content.AppsBadgeGlobal"] = "全局模板",
        ["Content.AppsBadgeTenant"] = "租户",
        ["Content.AppsEdit"] = "编辑",
        ["Content.AppsDelete"] = "删除",
        ["Content.AppsDeleteConfirmTitle"] = "删除应用",
        ["Content.AppsDeleteConfirmMsg"] = "删除后不可恢复，确认要删除该应用吗？",
        ["Content.AppsDeleteConfirmText"] = "删除",
        ["Content.AppsGenDescLabel"] = "应用描述",
        ["Content.AppsGenDescHint"] = "用一句话描述你想要的 BI 应用，AI 将生成 DSL。",
        ["Content.AppsGenDescPlaceholder"] = "例如：销售看板，按地区展示销售额与订单量",
        ["Content.AppsGenCodeLabel"] = "应用编码",
        ["Content.AppsGenCodeHint"] = "留空由系统生成（如 my-app-1733）。",
        ["Content.AppsGenCodePlaceholder"] = "可选",
        ["Content.AppsGenCancel"] = "取消",
        ["Content.AppsGenSubmit"] = "生成并创建",
        ["Content.AppsDslIntro"] = "应用 {0} 的声明式定义（AppDsl JSON）。保存将重新校验并覆盖。",
        ["Content.AppsDslGlobalWarning"] = "该应用为全局模板，不可修改。",
        ["Content.AppsDslFieldLabel"] = "DslJson",
        ["Content.AppsDslSave"] = "保存",
        ["Content.AppsMissingCodeOpen"] = "该记录缺少 code，无法打开详情。",
        ["Content.AppsMissingCodeEdit"] = "该记录缺少 code，无法编辑。",
        ["Content.AppsMissingCodeDelete"] = "该记录缺少 code，无法删除。",
        ["Content.AppsGenDescRequired"] = "应用描述必填。",
        ["Content.AppsGenSuccess"] = "应用已通过 AI 生成并创建。",
        ["Content.AppsGenFailed"] = "生成失败（HTTP {0}）。",
        ["Content.AppsReadFailed"] = "读取应用失败。",
        ["Content.AppsDslJsonEmpty"] = "DslJson 不能为空。",
        ["Content.AppsDslSaved"] = "应用 DSL 已保存。",
        ["Content.AppsDslSaveFailed"] = "保存失败（HTTP {0}）。",
        ["Content.AppsDeleteSuccess"] = "应用已删除。",
        ["Content.AppsDeleteFailed"] = "删除失败。",
        ["Content.AppsLoadFailed"] = "加载失败。",
        ["Content.AppDetailDesc"] = "应用详情：DSL 结构、页面与组件清单。",
        ["Content.AppDetailBack"] = "返回列表",
        ["Content.AppDetailRefresh"] = "刷新",
        ["Content.AppDetailDelete"] = "删除",
        ["Content.AppDetailLoading"] = "正在加载应用…",
        ["Content.AppDetailTabOverview"] = "概览",
        ["Content.AppDetailPanelBasic"] = "基本信息",
        ["Content.AppDetailTabComponents"] = "页面与组件",
        ["Content.AppDetailPanelComponents"] = "组件清单",
        ["Content.AppDetailEmptyComponentsTitle"] = "未解析到组件",
        ["Content.AppDetailEmptyComponentsText"] = "该应用的 DSL 中暂无可解析的组件定义。",
        ["Content.AppDetailTabDsl"] = "DSL",
        ["Content.AppDetailPanelDsl"] = "App DSL（只读）",
        ["Content.AppDetailDeleteConfirmTitle"] = "删除应用",
        ["Content.AppDetailDeleteConfirmMsg"] = "确认删除应用「{0}」？该操作不可撤销。",
        ["Content.AppDetailDeleteConfirmText"] = "删除",
        ["Content.AppDetailTitleDefault"] = "应用详情",
        ["Content.AppDetailDeleteSuccess"] = "应用已删除。",
        ["Content.AppDetailDeleteFailed"] = "删除失败（HTTP {0}）。",
        ["Content.AppDetailLoadFailed"] = "加载失败（{0}）。",
        ["Content.AskTurnMe"] = "我",
        ["Content.AskTurnAiSummary"] = "AI 解读",
        ["Content.AskTurnMeta"] = "耗时 {0} ms · 建议图表 {1} 个",
        ["Content.AskTurnChartDefault"] = "图表 {0}",
        ["Content.AskTurnViewLabel"] = "视图：",
        ["Content.AskTurnBar"] = "柱状",
        ["Content.AskTurnLine"] = "折线",
        ["Content.AskTurnPie"] = "饼图",
        ["Content.AskTurnHideLegend"] = "隐藏图例",
        ["Content.AskTurnShowLegend"] = "显示图例",
        ["Content.AskTurnCyclePalette"] = "换配色",
        ["Content.AskTurnStacked"] = "堆叠",
        ["Content.AskTurnUnstacked"] = "取消堆叠",
        ["Content.AskTurnArea"] = "面积",
        ["Content.AskTurnUnarea"] = "取消面积",
        ["Content.AskTurnMultiAxis"] = "多轴",
        ["Content.AskTurnUnmulti"] = "取消多轴",
        ["Content.AskTurnRowsTotal"] = "共 {0} 行",
        ["Content.AskTurnDrill"] = "下钻：",
        ["Content.AskTurnClearDrill"] = "清除下钻",
        ["Content.AskTurnExportCsv"] = "导出 CSV",
        ["Content.AskTurnExportExcel"] = "导出 Excel",
        ["Content.AskTurnQueryFailed"] = "查询失败：{0}",
        ["Content.AskTurnViewSql"] = "查看生成的 SQL",
        ["Content.AskTurnHideCompare"] = "隐藏对比",
        ["Content.AskTurnShowCompare"] = "对比原结果",
        ["Content.AskTurnOriginalResult"] = "原结果 · {0}",
        ["Content.AskTurnRefinedResult"] = "细化结果 · {0}",
        ["Content.AskTurnRefinePlaceholder"] = "例如：改成柱状图 / 隐藏图例 / 配色换成绿色",
        ["Content.AskTurnApplyAdjust"] = "应用调整",
        ["Content.AskTurnSemanticPlaceholder"] = "基于本轮结果继续追问，如：只看华东地区 / 改成按月统计",
        ["Content.AskTurnSemanticRefine"] = "语义细化",
        ["Content.AskTurnRefining"] = "查询中…",
        ["Content.AskTurnPublish"] = "发布为应用",
        ["Content.AskTurnPublishing"] = "发布中…",
        ["Content.AskTurnRefineNoCmd"] = "请输入调整指令。",
        ["Content.AskTurnRefineNoViz"] = "当前轮无可视化结果。",
        ["Content.AskTurnRefineUnrecognized"] = "未能识别指令（支持：改成柱状/折线/饼图、显示/隐藏图例、配色换绿/橙/红/灰/蓝）。",
        ["Content.AskTurnRefineApplied"] = "已应用视图调整（纯前端，未发起后端请求）。",
        ["Content.CommonRefresh"] = "刷新",
        ["Content.CommonCancel"] = "取消",
        ["Content.CommonCreate"] = "创建",
        ["Content.CommonSave"] = "保存",
        ["Content.CommonAdd"] = "添加",
        ["Content.CommonUsername"] = "用户名",
        ["Content.CommonDisplayName"] = "显示名",
        ["Content.CommonEmail"] = "邮箱",
        ["Content.CommonName"] = "名称",
        ["Content.CommonDescription"] = "描述",
        ["Content.CommonRole"] = "角色",
        ["Content.CommonUser"] = "用户",
        ["Content.CommonPermission"] = "权限",
        ["Content.CommonPermissions"] = "权限点",
        ["Content.CommonRoleCode"] = "角色编码",
        ["Content.CommonSelectPlaceholder"] = "— 请选择 —",
        ["Content.CommonOptional"] = "可选",
        ["Content.AdminIdentityTitle"] = "身份与权限",
        ["Content.AdminIdentityDesc"] = "管理用户、角色与权限分配，基于租户作用域的 RBAC。",
        ["Content.AdminIdentityCreateUser"] = "新建用户",
        ["Content.AdminIdentityCreateRole"] = "新建角色",
        ["Content.AdminIdentityLoading"] = "正在加载身份与权限…",
        ["Content.AdminIdentityStatUsers"] = "用户",
        ["Content.AdminIdentityStatUsersSub"] = "当前租户",
        ["Content.AdminIdentityStatRoles"] = "角色",
        ["Content.AdminIdentityStatRolesSub"] = "RBAC",
        ["Content.AdminIdentityStatPerms"] = "权限点",
        ["Content.AdminIdentityStatPermsSub"] = "可授予",
        ["Content.AdminIdentityPanelUsers"] = "用户",
        ["Content.AdminIdentityEmptyUsers"] = "暂无用户",
        ["Content.AdminIdentityEmptyUsersText"] = "用户是租户内可登录与操作的账号主体。",
        ["Content.AdminIdentityNoMatchUsers"] = "无匹配用户",
        ["Content.AdminIdentityAssignRole"] = "分配角色",
        ["Content.AdminIdentityPanelRoles"] = "角色",
        ["Content.AdminIdentityEmptyRoles"] = "暂无角色",
        ["Content.AdminIdentityEmptyRolesText"] = "角色聚合一组权限，可批量授予用户。",
        ["Content.AdminIdentityNoMatchRoles"] = "无匹配角色",
        ["Content.AdminIdentityEditPerms"] = "编辑权限",
        ["Content.AdminIdentityUsernamePh"] = "登录账号",
        ["Content.AdminIdentityInitialRole"] = "初始角色",
        ["Content.AdminIdentityNoRoles"] = "暂无可选角色",
        ["Content.AdminIdentityRoleCodePh"] = "如 order.manager",
        ["Content.AdminIdentityNoPerms"] = "暂无可选权限",
        ["Content.AdminIdentitySelectRole"] = "— 选择角色 —",
        ["Content.AdminIdentityModalEditPerms"] = "编辑角色权限",
        ["Content.AdminIdentityConfirmSavePermsTitle"] = "保存角色权限",
        ["Content.AdminIdentityConfirmSavePermsMsg"] = "确认覆盖该角色的权限集？变更对拥有此角色的用户立即生效，且需重新登录后在前端生效。",
        ["Content.AdminIdentityConfirmAssignTitle"] = "指派角色",
        ["Content.AdminIdentityConfirmAssignMsg"] = "确认为用户「{0}」指派角色「{1}」？",
        ["Content.AdminIdentityAssignHint"] = "为用户 {0} 指派角色（角色可为全局或本租户）。",
        ["Content.AdminIdentityPermHint"] = "角色 {0}（{1}）的权限集（全量替换）。",
        ["Content.AdminIdentityUsernameRequired"] = "用户名必填。",
        ["Content.AdminIdentityUserCreated"] = "用户 {0} 已创建。",
        ["Content.AdminIdentityCreateFailed"] = "创建失败（HTTP {0}）。",
        ["Content.AdminIdentityRoleCodeRequired"] = "角色编码必填。",
        ["Content.AdminIdentityRoleCreated"] = "角色 {0} 已创建。",
        ["Content.AdminIdentitySelectRoleRequired"] = "请选择角色。",
        ["Content.AdminIdentityAssigned"] = "已为 {0} 指派角色 {1}。",
        ["Content.AdminIdentityAssignFailed"] = "指派失败（HTTP {0}）。",
        ["Content.AdminIdentityPermsUpdated"] = "角色 {0} 权限已更新。",
        ["Content.AdminIdentitySaveFailed"] = "保存失败（HTTP {0}）。",
        ["Content.AdminPlatformAdminsDesc"] = "管理平台治理账号：新增、停用 / 启用、重置口令，并审计所有治理操作。始终至少保留一名有效管理员。",
        ["Content.AdminPlatformAdminsCreate"] = "新建管理员",
        ["Content.AdminPlatformAdminsTabAdmins"] = "管理员",
        ["Content.AdminPlatformAdminsPanelAdmins"] = "平台管理员",
        ["Content.AdminPlatformAdminsEmptyAdminsTitle"] = "暂无平台管理员",
        ["Content.AdminPlatformAdminsEmptyAdminsText"] = "使用「新建管理员」添加首位或额外的平台治理账号。",
        ["Content.AdminPlatformAdminsTabAudit"] = "操作审计",
        ["Content.AdminPlatformAdminsPanelAudit"] = "治理操作审计",
        ["Content.AdminPlatformAdminsEmptyAuditTitle"] = "暂无治理审计",
        ["Content.AdminPlatformAdminsEmptyAuditText"] = "对平台管理员的增、停用、启用、重置口令操作都会记录在此。",
        ["Content.AdminPlatformAdminsModalCreate"] = "新建平台管理员",
        ["Content.AdminPlatformAdminsUsernamePh"] = "登录账号",
        ["Content.AdminPlatformAdminsInitialPassword"] = "初始口令",
        ["Content.AdminPlatformAdminsPasswordPh"] = "至少 8 位",
        ["Content.AdminPlatformAdminsModalReset"] = "重置口令",
        ["Content.AdminPlatformAdminsResetHint"] = "为 {0} 设置新口令（至少 8 位）。旧令牌将立即失效。",
        ["Content.AdminPlatformAdminsNewPassword"] = "新口令",
        ["Content.AdminPlatformAdminsResetButton"] = "重置",
        ["Content.AdminPlatformAdminsResetPassword"] = "重置口令",
        ["Content.AdminPlatformAdminsDisableTitle"] = "停用平台管理员",
        ["Content.AdminPlatformAdminsDisableMsg"] = "确认停用「{0}」？该账号将立即无法登录。",
        ["Content.AdminPlatformAdminsDisableBtn"] = "停用",
        ["Content.AdminPlatformAdminsEnableTitle"] = "启用平台管理员",
        ["Content.AdminPlatformAdminsEnableMsg"] = "确认重新启用「{0}」？",
        ["Content.AdminPlatformAdminsEnableBtn"] = "启用",
        ["Content.AdminPlatformAdminsColStatus"] = "状态",
        ["Content.AdminPlatformAdminsColCreatedTime"] = "创建时间",
        ["Content.AdminPlatformAdminsColAction"] = "操作",
        ["Content.AdminPlatformAdminsColActor"] = "操作人",
        ["Content.AdminPlatformAdminsColResult"] = "结果",
        ["Content.AdminPlatformAdminsColTime"] = "时间",
        ["Content.AdminPlatformAdminsCreateRequired"] = "用户名与初始口令均必填。",
        ["Content.AdminPlatformAdminsInitPasswordTooShort"] = "初始口令至少 8 位。",
        ["Content.AdminPlatformAdminsCreated"] = "平台管理员 {0} 已创建。",
        ["Content.AdminPlatformAdminsCreateFailed"] = "创建失败（HTTP {0}）。",
        ["Content.AdminPlatformAdminsNewPasswordTooShort"] = "新口令至少 8 位。",
        ["Content.AdminPlatformAdminsResetDone"] = "{0} 的口令已重置，旧令牌已失效。",
        ["Content.AdminPlatformAdminsResetFailed"] = "重置失败（HTTP {0}）。",
        ["Content.AdminPlatformAdminsDisabled"] = "{0} 已停用。",
        ["Content.AdminPlatformAdminsDisableFailed"] = "停用失败（HTTP {0}）。",
        ["Content.AdminPlatformAdminsEnabled"] = "{0} 已启用。",
        ["Content.AdminPlatformAdminsEnableFailed"] = "启用失败（HTTP {0}）。",
        ["Content.AdminPlatformAdminsActAdd"] = "新增管理员",
        ["Content.AdminPlatformAdminsActDisable"] = "停用管理员",
        ["Content.AdminPlatformAdminsActEnable"] = "启用管理员",
        ["Content.AdminPlatformAdminsActReset"] = "重置口令",
        ["Content.AdminTenantsDesc"] = "管理多租户：创建租户、配置隔离作用域与默认配额，平台运营入口。",
        ["Content.AdminTenantsListTitle"] = "租户列表",
        ["Content.AdminTenantsSearchPlaceholder"] = "搜索租户编码 / 名称…",
        ["Content.AdminTenantsEmptyTitle"] = "暂无租户",
        ["Content.AdminTenantsEmptyText"] = "创建租户以隔离数据与配额作用域。",
        ["Content.AdminTenantsLoadingText"] = "正在加载租户…",
        ["Content.AdminTenantsNew"] = "新建租户",
        ["Content.AdminTenantsStatTotal"] = "租户总数",
        ["Content.AdminTenantsStatTotalSub"] = "平台级",
        ["Content.AdminTenantsStatEnabled"] = "已启用",
        ["Content.AdminTenantsStatEnabledSub"] = "使用中",
        ["Content.AdminTenantsStatDisabled"] = "已停用",
        ["Content.AdminTenantsStatDisabledSub"] = "未启用",
        ["Content.AdminTenantsEdit"] = "编辑",
        ["Content.AdminTenantsDisable"] = "停用",
        ["Content.AdminTenantsEnable"] = "启用",
        ["Content.AdminTenantsEnableTitle"] = "启用租户",
        ["Content.AdminTenantsDisableTitle"] = "停用租户",
        ["Content.AdminTenantsSettings"] = "设置",
        ["Content.AdminTenantsCreateTitle"] = "新建租户",
        ["Content.AdminTenantsCodeLabel"] = "租户编码",
        ["Content.AdminTenantsCodePlaceholder"] = "如：t-acme",
        ["Content.AdminTenantsNameLabel"] = "租户名称",
        ["Content.AdminTenantsNamePlaceholder"] = "如：Acme 零售",
        ["Content.AdminTenantsAdminUserLabel"] = "首位租户管理员用户名",
        ["Content.AdminTenantsAdminUserPlaceholder"] = "如：acme-admin",
        ["Content.AdminTenantsAdminDisplayNameLabel"] = "管理员显示名",
        ["Content.AdminTenantsAdminDisplayNamePlaceholder"] = "如：Acme 管理员",
        ["Content.AdminTenantsAdminEmailLabel"] = "管理员邮箱",
        ["Content.AdminTenantsAdminPasswordLabel"] = "管理员初始口令",
        ["Content.AdminTenantsAdminPasswordHint"] = "至少 8 位，建议首次登录后立即修改。",
        ["Content.AdminTenantsLanguagesLabel"] = "租户可用语言",
        ["Content.AdminTenantsLanguagesHint"] = "用户只能在启用的语言之间切换。",
        ["Content.AdminTenantsDefaultLangLabel"] = "默认显示语言",
        ["Content.AdminTenantsEditTitle"] = "编辑租户 · {0}",
        ["Content.AdminTenantsEditLanguagesLabel"] = "租户支持语言",
        ["Content.AdminTenantsEditLanguagesHint"] = "语言范围来自平台多语言中心。",
        ["Content.AdminTenantsEditDefaultLangLabel"] = "默认语言",
        ["Content.AdminTenantsSaveEdit"] = "保存修改",
        ["Content.AdminTenantsSettingTitle"] = "租户设置 · {0}",
        ["Content.AdminTenantsSettingEmptyTitle"] = "暂无设置",
        ["Content.AdminTenantsSettingEmptyText"] = "为该租户新增一条配置项（Key/Value/DataType）。",
        ["Content.AdminTenantsSettingKeyLabel"] = "配置 Key",
        ["Content.AdminTenantsSettingKeyPlaceholder"] = "如：DefaultQuota",
        ["Content.AdminTenantsSettingValueLabel"] = "配置 Value",
        ["Content.AdminTenantsSettingValuePlaceholder"] = "如：1000",
        ["Content.AdminTenantsSettingTypeLabel"] = "数据类型",
        ["Content.AdminTenantsClose"] = "关闭",
        ["Content.AdminTenantsSaveSetting"] = "保存配置",
        ["Content.AdminTenantsCodeRequired"] = "租户编码必填。",
        ["Content.AdminTenantsAdminUserRequired"] = "首位租户管理员用户名必填。",
        ["Content.AdminTenantsPasswordTooShort"] = "管理员初始口令至少 8 位。",
        ["Content.AdminTenantsLangRequired"] = "至少选择一种租户语言。",
        ["Content.AdminTenantsCodeExists"] = "租户编码已存在。",
        ["Content.AdminTenantsSaveFailed"] = "保存失败。",
        ["Content.AdminTenantsCreated"] = "租户及首位租户管理员已创建。",
        ["Content.AdminTenantsEditLangRequired"] = "至少选择一种语言。",
        ["Content.AdminTenantsUpdated"] = "租户基本信息与语言配置已更新。",
        ["Content.AdminTenantsMissingId"] = "该记录缺少 id。",
        ["Content.AdminTenantsOpFailed"] = "操作失败。",
        ["Content.AdminTenantsEnabled"] = "租户已启用。",
        ["Content.AdminTenantsDisabled"] = "租户已停用。",
        ["Content.AdminTenantsSettingMissingId"] = "该记录缺少 id，无法打开设置。",
        ["Content.AdminTenantsSettingKeyRequired"] = "配置 Key 必填。",
        ["Content.AdminTenantsSettingKeyExists"] = "配置 Key 已存在。",
        ["Content.AdminTenantsSettingSaved"] = "租户配置已保存。",
        ["Content.AdminTenantsConfirmMsg"] = "确认{0}租户「{1}」？该操作会影响其数据访问与隔离作用域。",
        ["Content.AdminLocalizationDesc"] = "平台维护语言与标准文本；租户自动继承，并只覆盖自己的差异文案。",
        ["Content.AdminLocalizationRailTitle"] = "语言目录",
        ["Content.AdminLocalizationPendingTitle"] = "尚未翻译的键数",
        ["Content.AdminLocalizationPendingChip"] = "待翻译",
        ["Content.AdminLocalizationDisabledChip"] = "已停用",
        ["Content.AdminLocalizationMoveUp"] = "上移",
        ["Content.AdminLocalizationMoveDown"] = "下移",
        ["Content.AdminLocalizationEditName"] = "编辑名称",
        ["Content.AdminLocalizationDisable"] = "停用",
        ["Content.AdminLocalizationEnable"] = "启用",
        ["Content.AdminLocalizationAddLanguage"] = "＋ 添加语言",
        ["Content.AdminLocalizationSystemTexts"] = "系统文本",
        ["Content.AdminLocalizationPlatformBaselineDesc"] = "正在维护平台基线，修改会自动影响未覆盖该文本的租户。",
        ["Content.AdminLocalizationTenantInheritDesc"] = "默认继承平台文本；标记为「租户专属」的项目仅对当前租户生效。",
        ["Content.AdminLocalizationAddText"] = "＋ 新增文本键",
        ["Content.AdminLocalizationPlatformBadge"] = "平台基线",
        ["Content.AdminLocalizationInheritBadge"] = "继承 + 差异覆盖",
        ["Content.AdminLocalizationLoadingText"] = "正在加载语言资源…",
        ["Content.AdminLocalizationPlatformDefault"] = "平台默认",
        ["Content.AdminLocalizationPlatformText"] = "平台文本",
        ["Content.AdminLocalizationTenantText"] = "租户显示文本",
        ["Content.AdminLocalizationTenantOverride"] = "租户专属",
        ["Content.AdminLocalizationRestoreInherit"] = "恢复继承",
        ["Content.AdminLocalizationBaselineChip"] = "基线",
        ["Content.AdminLocalizationInheritedChip"] = "已继承",
        ["Content.AdminLocalizationAddLangTitle"] = "添加平台语言",
        ["Content.AdminLocalizationCultureCode"] = "Culture 代码",
        ["Content.AdminLocalizationDisplayName"] = "显示名称",
        ["Content.AdminLocalizationNativeName"] = "本地名称",
        ["Content.AdminLocalizationCopyFrom"] = "初始文本复制自",
        ["Content.AdminLocalizationCulturePlaceholder"] = "如：fr-FR",
        ["Content.AdminLocalizationDisplayNamePlaceholder"] = "如：法语（法国）",
        ["Content.AdminLocalizationNativePlaceholder"] = "如：Français",
        ["Content.AdminLocalizationCreateLanguage"] = "创建语言",
        ["Content.AdminLocalizationEditLangTitle"] = "编辑语言名称",
        ["Content.AdminLocalizationAddTextTitle"] = "新增系统文本键",
        ["Content.AdminLocalizationResourceKey"] = "资源键",
        ["Content.AdminLocalizationCurrentText"] = "当前语言文本",
        ["Content.AdminLocalizationResourceKeyPlaceholder"] = "如：Page.Title.订单",
        ["Content.AdminLocalizationSaveFailed"] = "保存失败。",
        ["Content.AdminLocalizationPlatformUpdated"] = "平台文本已更新。",
        ["Content.AdminLocalizationTenantSaved"] = "租户专属文本已保存。",
        ["Content.AdminLocalizationRestoreFailed"] = "恢复失败。",
        ["Content.AdminLocalizationRestored"] = "已恢复继承平台文本。",
        ["Content.AdminLocalizationCreateFailed"] = "创建失败。",
        ["Content.AdminLocalizationCreated"] = "语言已创建，可开始维护对应文本。",
        ["Content.AdminLocalizationNameUpdated"] = "语言名称已更新。",
        ["Content.AdminLocalizationOpFailed"] = "操作失败。",
        ["Content.AdminLocalizationEnabled"] = "语言已启用。",
        ["Content.AdminLocalizationDisabled"] = "语言已停用，相关租户默认语言已迁移。",
        ["Content.AdminLocalizationReorderFailed"] = "排序失败。",
        ["Content.AdminTenantMembersDesc"] = "管理用户与额外可切换租户之间的成员关系：为用户授予跨租户切换资格，或撤销其成员资格。",
        ["Content.AdminTenantMembersSearchPlaceholder"] = "搜索用户名 / 租户…",
        ["Content.AdminTenantMembersEmptyTitle"] = "暂无租户成员关系",
        ["Content.AdminTenantMembersEmptyText"] = "使用「添加成员」为用户授予额外的可切换租户（主租户为隐式成员，不在本表列出）。",
        ["Content.AdminTenantMembersLoadingText"] = "正在加载成员关系…",
        ["Content.AdminTenantMembersAddBtn"] = "添加成员",
        ["Content.AdminTenantMembersStatMembers"] = "成员关系",
        ["Content.AdminTenantMembersStatMembersSub"] = "显式",
        ["Content.AdminTenantMembersStatDefault"] = "默认切换",
        ["Content.AdminTenantMembersStatDefaultSub"] = "标记默认",
        ["Content.AdminTenantMembersStatDisabled"] = "指向停用租户",
        ["Content.AdminTenantMembersStatDisabledSub"] = "需注意",
        ["Content.AdminTenantMembersRemoveBtn"] = "移除",
        ["Content.AdminTenantMembersModalTitle"] = "添加租户成员",
        ["Content.AdminTenantMembersUserIdLabel"] = "用户 ID",
        ["Content.AdminTenantMembersUserIdPlaceholder"] = "目标用户的 Id",
        ["Content.AdminTenantMembersTenantIdLabel"] = "目标租户 ID",
        ["Content.AdminTenantMembersTenantIdPlaceholder"] = "用户将可切换到的租户 Id",
        ["Content.AdminTenantMembersDefaultLabel"] = "默认切换",
        ["Content.AdminTenantMembersDefaultHint"] = "勾选后该租户成为此用户的默认切换目标（主租户始终为默认）。",
        ["Content.AdminTenantMembersSetDefault"] = "设为默认切换租户",
        ["Content.AdminTenantMembersRemoveTitle"] = "移除租户成员",
        ["Content.AdminTenantMembersRemoveConfirm"] = "移除",
        ["Content.AdminTenantMembersRemoveMsg"] = "确认移除用户「{0} (#{1})」与租户 (#{2}) 的成员关系？该用户将不再能切换到此租户（主租户不可移除）。",
        ["Content.AdminTenantMembersColUser"] = "用户",
        ["Content.AdminTenantMembersColTenant"] = "租户",
        ["Content.AdminTenantMembersColDefault"] = "默认",
        ["Content.AdminTenantMembersColTenantEnabled"] = "租户启用",
        ["Content.AdminTenantMembersEnabled"] = "启用",
        ["Content.AdminTenantMembersDisabled"] = "停用",
        ["Content.AdminTenantMembersColCreated"] = "创建时间",
        ["Content.AdminTenantMembersListTitle"] = "成员关系",
        ["Content.AdminTenantMembersUserIdRequired"] = "用户 ID 必填且须大于 0。",
        ["Content.AdminTenantMembersTenantIdRequired"] = "目标租户 ID 必填且须大于 0。",
        ["Content.AdminTenantMembersAddFailedExists"] = "添加失败：用户或租户不存在，或已是成员。",
        ["Content.AdminTenantMembersAddFailed"] = "添加失败。",
        ["Content.AdminTenantMembersAdded"] = "已添加租户成员关系。",
        ["Content.AdminTenantMembersRemoveFailed"] = "移除失败。",
        ["Content.AdminTenantMembersRemoved"] = "已移除该租户成员关系。",
        ["Content.SharedConfirmTitle"] = "确认操作",
        ["Content.SharedConfirm"] = "确认",
        ["Content.SharedLoading"] = "加载中…",
        ["Content.SharedColActions"] = "操作",
        ["Content.SharedEmptyTitle"] = "暂无数据",
        ["Content.SharedRefresh"] = "刷新",
        ["Content.SharedSearchPlaceholder"] = "搜索…",
        ["Content.SharedClose"] = "关闭",
        ["Content.SharedPrevPage"] = "上一页",
        ["Content.SharedNextPage"] = "下一页",
        ["Content.SharedPageSummary"] = "第 {0} / {1} 页 · 共 {2} 条",
        ["Content.SharedSearch"] = "搜索",
        ["Content.SharedClear"] = "清空",
        ["Content.SharedTenantSwitch"] = "切换租户",
        ["Content.SharedTenantCurrent"] = "当前：租户 {0}（主租户 {1}）",
        ["Content.SharedTenantSwitchFailed"] = "切换失败",
        ["Content.SharedAuthChecking"] = "正在校验会话…",
        ["Content.SharedAuthRequiredTitle"] = "需要登录",
        ["Content.SharedAuthRequiredText"] = "该页面需要登录后访问，请先登录你的账号。",
        ["Content.SharedAuthGoLogin"] = "前往登录",
        ["Content.SharedPermDeniedTitle"] = "无访问权限",
        ["Content.SharedPermDeniedText"] = "当前账号缺少访问该页面所需的权限，请联系管理员。",
        ["Content.SharedBackHome"] = "返回首页",
        ["Content.SharedDataSource"] = "数据源",
        ["Content.SharedNoDataTitle"] = "没有返回数据",
        ["Content.SharedNoDataText"] = "本次查询未返回任何行。",
        ["Content.SharedViewSql"] = "查看生成的 SQL",
        ["Content.SharedCopySql"] = "复制 SQL",
        ["Content.SharedCopied"] = "已复制",
        ["Content.SharedCopyFailed"] = "复制失败，请手动选择",
        ["Content.SharedBreadcrumb"] = "面包屑",
        ["Content.ErrForbiddenTitle"] = "没有访问权限",
        ["Content.ErrForbiddenText"] = "当前账号缺少访问该资源所需的权限，或该资源属于其他租户。",
        ["Content.ErrNotFoundTitle"] = "页面不存在",
        ["Content.ErrNotFoundText"] = "该地址没有对应的页面，可能是链接已失效或输入有误。",
        ["Content.ErrServerTitle"] = "服务出现异常",
        ["Content.ErrServerText"] = "请求处理过程中发生未预期的错误，请稍后重试；若持续出现，请联系管理员并提供追踪 ID。",
        ["Content.ErrBackToWorkbench"] = "返回工作台",
        ["Content.ErrBack"] = "返回上一页",
        ["Content.ErrGoAsk"] = "去提问",
        ["Content.ErrReload"] = "重新加载",
        ["Content.AdminQuotaDesc"] = "查看与配置租户资源配额：问数次数、Token、存储与并发等，超阈预警。",
        ["Content.AdminQuotaLoading"] = "正在加载配额…",
        ["Content.AdminQuotaPanelTitle"] = "当前租户配额",
        ["Content.AdminQuotaEmptyTitle"] = "暂无配额数据",
        ["Content.AdminQuotaEmptyText"] = "联系平台管理员为当前租户配置资源配额。",
        ["Content.AdminQuotaTarget"] = "管理范围",
        ["Content.AdminQuotaPlatformDefaults"] = "平台默认配额",
        ["Content.AdminQuotaSelectTenant"] = "选择租户以查看继承和覆盖策略",
        ["Content.AdminQuotaResource"] = "资源",
        ["Content.AdminQuotaLimit"] = "上限",
        ["Content.AdminQuotaUsed"] = "已用",
        ["Content.AdminQuotaRemaining"] = "剩余",
        ["Content.AdminQuotaWindow"] = "周期",
        ["Content.AdminQuotaPeriod"] = "当前周期键",
        ["Content.AdminQuotaSource"] = "策略来源",
        ["Content.AdminQuotaPlatformSource"] = "平台默认",
        ["Content.AdminQuotaOverrideSource"] = "租户覆盖",
        ["Content.AdminQuotaInheritedSource"] = "继承平台",
        ["Content.AdminQuotaEditPolicy"] = "编辑策略",
        ["Content.AdminQuotaEditUsage"] = "维护用量",
        ["Content.AdminQuotaRestoreInheritance"] = "恢复继承",
        ["Content.AdminQuotaPolicyTitle"] = "编辑配额策略 · {0}",
        ["Content.AdminQuotaUsageTitle"] = "维护当前用量 · {0}",
        ["Content.AdminQuotaPolicySaved"] = "配额策略已保存。",
        ["Content.AdminQuotaUsageSaved"] = "当前周期用量已更新。",
        ["Content.AdminQuotaInheritanceRestored"] = "租户覆盖已移除，现已继承平台默认。",
        ["Content.AdminQuotaSaveFailed"] = "配额保存失败。",
        ["Content.AdminQuotaTenantRequired"] = "请先选择一个实际租户。",
        ["Content.AdminQuotaNonnegative"] = "数值不能小于 0。",
        ["Content.AdminQuotaUsers"] = "用户数",
        ["Content.AdminQuotaApps"] = "应用数",
        ["Content.AdminQuotaAgents"] = "智能体数",
        ["Content.AdminQuotaDashboards"] = "仪表盘数",
        ["Content.AdminQuotaDataSources"] = "数据源数",
        ["Content.AdminQuotaApiCalls"] = "每月 API 调用",
        ["Content.AdminQuotaStorage"] = "存储空间（MB）",
        ["Content.AdminQuotaWindowTotal"] = "累计",
        ["Content.AdminQuotaWindowMonthly"] = "每月",
        ["Content.AdminQuotaWindowDaily"] = "每日",
        ["Content.AdminThemesDesc"] = "为租户指派或创建主题蓝图，统一视觉风格；个人偏好请在「主题编辑器」中调整。",
        ["Content.AdminThemesPanelTitle"] = "租户主题",
        ["Content.AdminThemesEmptyTitle"] = "主题后端待接入",
        ["Content.AdminThemesEmptyText"] = "租户级主题由 P7.4 的 api/themes 提供，前端编辑器已就绪（见「主题编辑器」）。待管理端点上线后此处列出租户主题。",
        ["Content.AdminThemesOpenEditor"] = "打开主题编辑器",
        ["Content.ModelAccountsDescQwenPlus"] = "通义千问，中文业务理解强",
        ["Content.ModelAccountsDescQwenMax"] = "通义千问旗舰，复杂推理",
        ["Content.ModelAccountsDescGpt4o"] = "通用能力强",
        ["Content.ModelAccountsDescAzureOpenAI"] = "企业合规部署",
        ["Content.ModelAccountsDescDeepSeek"] = "高性价比推理",
        ["Content.DataSourceDetailTitle"] = "数据源 #{0}",
        ["Content.DataSourceDetailDesc"] = "数据源的授权清单与行级安全策略（RLS）。",
        ["Content.LoginPasswordNotice"] = "P0-04A 起登录校验口令：未设置口令的账户需先由管理员初始化。令牌携带安全戳，口令/角色变更后旧令牌立即失效。",
        ["Content.LoginBootstrapDisplayName"] = "平台系统管理员",
        ["Content.DashboardsCreateTitle"] = "新建仪表盘",
        ["Content.AppsCreateTitle"] = "新建应用（自然语言生成）",
        ["Content.AppsEditDslTitle"] = "编辑应用 DSL",
        ["Content.AgentTitle"] = "智能体 / Copilot",
        ["Content.AgentDesc"] = "编排多步分析任务的智能体：规划、调用工具链、异常归因，并与 Ask 协同。",
        ["Content.AgentSearchPlaceholder"] = "搜索智能体…",
        ["Content.AgentEmptyTitle"] = "暂无智能体",
        ["Content.AgentEmptyText"] = "智能体把「取数 → 清洗 → 归因 → 成稿」串成可复用的工作流，适合周期性经营分析。",
        ["Content.AgentLoadingText"] = "正在加载智能体…",
        ["Content.AgentCreate"] = "新建智能体",
        ["Content.AgentTileAgents"] = "智能体",
        ["Content.AgentTileTools"] = "可用工具",
        ["Content.AgentRowDetail"] = "详情",
        ["Content.AgentRowRun"] = "运行",
        ["Content.AgentRowDelete"] = "删除",
        ["Content.AgentDeleteTitle"] = "删除智能体计划",
        ["Content.AgentDeleteMsg"] = "删除后不可恢复，确认要删除该计划吗？",
        ["Content.AgentDeleteConfirm"] = "删除",
        ["Content.AgentToolsPanelTitle"] = "可用工具",
        ["Content.AgentToolsEmptyTitle"] = "暂无工具",
        ["Content.AgentToolsEmptyText"] = "后端未注册可用的智能体工具。",
        ["Content.AgentColName"] = "名称",
        ["Content.AgentColDescription"] = "描述",
        ["Content.AgentColStatus"] = "状态",
        ["Content.AgentStatusDraft"] = "草稿",
        ["Content.AgentOpenMissingCode"] = "该记录缺少 code，无法打开计划详情。",
        ["Content.AgentRunQueued"] = "运行已排队。",
        ["Content.AgentRunTriggered"] = "已触发运行：{0}",
        ["Content.AgentComposerPending"] = "智能体编排器将在 S2 阶段接入。",
        ["Content.AgentDeleteMissingCode"] = "该记录缺少 code，无法删除。",
        ["Content.AgentDeleteFailed"] = "删除失败。",
        ["Content.AgentDeleted"] = "智能体计划已删除。",
        ["Content.DashboardDetailDesc"] = "仪表盘详情：基本信息、组件构成与渲染结果。",
        ["Content.DashboardDetailBack"] = "返回列表",
        ["Content.DashboardDetailLoading"] = "正在加载仪表盘…",
        ["Content.DashboardDetailTabOverview"] = "概览",
        ["Content.DashboardDetailInfoTitle"] = "基本信息",
        ["Content.DashboardDetailTabComponents"] = "组件",
        ["Content.DashboardDetailComponentsTitle"] = "组件构成",
        ["Content.DashboardDetailCompEmptyTitle"] = "未解析到组件",
        ["Content.DashboardDetailCompEmptyText"] = "该仪表盘尚未配置组件，或 DSL 结构暂不支持前端解析。",
        ["Content.DashboardDetailTypeAndId"] = "类型 {0} · 标识 {1}",
        ["Content.DashboardDetailTabData"] = "数据",
        ["Content.DashboardDetailRowCount"] = "共 {0} 行",
        ["Content.DashboardDetailDataEmptyTitle"] = "暂无渲染数据",
        ["Content.DashboardDetailDataEmptyText"] = "点击渲染后端会执行一次取数，若仍无数据请检查仪表盘配置与数据源可用性。",
        ["Content.DashboardDetailRendering"] = "渲染中…",
        ["Content.DashboardDetailRunRender"] = "执行渲染",
        ["Content.DashboardDetailDefaultTitle"] = "仪表盘详情",
        ["Content.PlatformAdminScopesDesc"] = "为平台管理员设定可管理的租户范围：默认管理全部租户，也可显式限定为特定租户。超出授权范围的租户操作将被拒绝。",
        ["Content.PlatformAdminScopesPanelTitle"] = "平台管理员与范围",
        ["Content.PlatformAdminScopesEmptyTitle"] = "暂无平台管理员",
        ["Content.PlatformAdminScopesEmptyText"] = "请先在「平台管理员」中添加治理账号。",
        ["Content.PlatformAdminScopesModalTitle"] = "设置租户范围",
        ["Content.PlatformAdminScopesModalTitleUser"] = "设置 {0} 的租户范围",
        ["Content.PlatformAdminScopesLoadingScope"] = "加载范围…",
        ["Content.PlatformAdminScopesAllTenants"] = "管理全部租户（默认）",
        ["Content.PlatformAdminScopesOnlySelected"] = "仅以下被勾选的租户可被该管理员管理：",
        ["Content.PlatformAdminScopesNoTenantAccess"] = "当前账号无权查看租户列表，无法细化范围（仅可设为「全部租户」）。",
        ["Content.PlatformAdminScopesColScope"] = "管理范围",
        ["Content.PlatformAdminScopesSetScope"] = "设置范围",
        ["Content.PlatformAdminScopesAllTenantsText"] = "全部租户",
        ["Content.PlatformAdminScopesNTenants"] = "{0} 个租户",
        ["Content.PlatformAdminScopesToastAll"] = "{0} 已设为管理全部租户。",
        ["Content.PlatformAdminScopesToastUpdated"] = "{0} 的管理范围已更新（{1} 个租户）。",
        ["Content.PlatformAdminScopesSaveFailed"] = "保存失败（HTTP {0}）。",
        ["Content.SelfRegistrationAdminDesc"] = "查看自助注册开放状态与配置。默认关闭，由平台按环境配置开启。",
        ["Content.SelfRegistrationAdminCurrentStatus"] = "当前状态",
        ["Content.SelfRegistrationAdminColEnabled"] = "是否开放",
        ["Content.SelfRegistrationAdminColApproval"] = "需管理员审批",
        ["Content.SelfRegistrationAdminColCaptcha"] = "需验证码",
        ["Content.SelfRegistrationAdminColDomains"] = "允许邮箱域名",
        ["Content.SelfRegistrationAdminColDefaultLang"] = "默认语言",
        ["Content.SelfRegistrationAdminColAvailLang"] = "可用语言",
        ["Content.SelfRegistrationAdminConfigNoteTitle"] = "配置说明",
        ["Content.SelfRegistrationAdminConfigNote1"] = "自助注册默认关闭（DEC-04：默认关闭，平台按环境开启）。开放方式：在部署配置中将 ",
        ["Content.SelfRegistrationAdminConfigNote2"] = " 设为 ",
        ["Content.SelfRegistrationAdminConfigNote3"] = " 并重启服务。审批 / 验证码为待裁决特性，尚未实现——开启相关开关会导致注册被拒绝；运行期不可在此页直接切换，须经治理评估后实施。",
        ["Content.SelfRegistrationAdminLoadFailed"] = "无法加载自助注册配置。",
        ["Content.SelfRegistrationAdminBadgeOpen"] = "已开放",
        ["Content.SelfRegistrationAdminBadgeClosed"] = "未开放",
        ["Content.CommonYes"] = "是",
        ["Content.CommonNo"] = "否",
        ["Content.AuditTitle"] = "审计日志",
        ["Content.AuditDesc"] = "记录关键操作与访问轨迹，支持按操作 / 资源 / 操作人 / 时间检索，满足合规要求。",
        ["Content.AuditSearchPlaceholder"] = "搜索操作 / 用户 / 资源…",
        ["Content.AuditEmptyTitle"] = "暂无审计记录",
        ["Content.AuditEmptyText"] = "关键写操作与登录事件会被记录到这里，便于追溯与合规审查。",
        ["Content.AuditLoadingText"] = "正在加载审计日志…",
        ["Content.AuditExportCsv"] = "导出 CSV",
        ["Content.AuditFilterAction"] = "操作 action",
        ["Content.AuditFilterEntity"] = "资源 entityType",
        ["Content.AuditFilterActor"] = "操作人 actor",
        ["Content.AuditReset"] = "重置",
        ["Content.AuditStatTotal"] = "日志总数",
        ["Content.AuditStatTotalSub"] = "本租户",
        ["Content.AuditStatFiltered"] = "筛选命中",
        ["Content.AuditStatFilteredSub"] = "当前条件",
        ["Content.AuditStatToday"] = "今日",
        ["Content.AuditStatTodaySub"] = "当天事件",
        ["Content.AuditNoExport"] = "没有可导出的记录。",
        ["Content.AuditExported"] = "已导出 {0} 条审计记录。",
        ["Content.PlatformAdminScopesDesc"] = "为平台管理员设定可管理的租户范围：默认管理全部租户，也可显式限定为特定租户。超出授权范围的租户操作将被拒绝。",
        ["Content.PlatformAdminScopesPanelTitle"] = "平台管理员与范围",
        ["Content.PlatformAdminScopesEmptyTitle"] = "暂无平台管理员",
        ["Content.PlatformAdminScopesEmptyText"] = "请先在「平台管理员」中添加治理账号。",
        ["Content.PlatformAdminScopesModalTitle"] = "设置租户范围",
        ["Content.PlatformAdminScopesModalTitleUser"] = "设置 {0} 的租户范围",
        ["Content.PlatformAdminScopesLoadingScope"] = "加载范围…",
        ["Content.PlatformAdminScopesAllTenants"] = "管理全部租户（默认）",
        ["Content.PlatformAdminScopesOnlySelected"] = "仅以下被勾选的租户可被该管理员管理：",
        ["Content.PlatformAdminScopesNoTenantAccess"] = "当前账号无权查看租户列表，无法细化范围（仅可设为「全部租户」）。",
        ["Content.PlatformAdminScopesColScope"] = "管理范围",
        ["Content.PlatformAdminScopesSetScope"] = "设置范围",
        ["Content.PlatformAdminScopesAllTenantsText"] = "全部租户",
        ["Content.PlatformAdminScopesNTenants"] = "{0} 个租户",
        ["Content.PlatformAdminScopesToastAll"] = "{0} 已设为管理全部租户。",
        ["Content.PlatformAdminScopesToastUpdated"] = "{0} 的管理范围已更新（{1} 个租户）。",
        ["Content.PlatformAdminScopesSaveFailed"] = "保存失败（HTTP {0}）。",
        ["Content.SelfRegistrationAdminDesc"] = "查看自助注册开放状态与配置。默认关闭，由平台按环境配置开启。",
        ["Content.SelfRegistrationAdminCurrentStatus"] = "当前状态",
        ["Content.SelfRegistrationAdminColEnabled"] = "是否开放",
        ["Content.SelfRegistrationAdminColApproval"] = "需管理员审批",
        ["Content.SelfRegistrationAdminColCaptcha"] = "需验证码",
        ["Content.SelfRegistrationAdminColDomains"] = "允许邮箱域名",
        ["Content.SelfRegistrationAdminColDefaultLang"] = "默认语言",
        ["Content.SelfRegistrationAdminColAvailLang"] = "可用语言",
        ["Content.SelfRegistrationAdminConfigNoteTitle"] = "配置说明",
        ["Content.SelfRegistrationAdminConfigNote1"] = "自助注册默认关闭（DEC-04：默认关闭，平台按环境开启）。开放方式：在部署配置中将 ",
        ["Content.SelfRegistrationAdminConfigNote2"] = " 设为 ",
        ["Content.SelfRegistrationAdminConfigNote3"] = " 并重启服务。审批 / 验证码为待裁决特性，尚未实现——开启相关开关会导致注册被拒绝；运行期不可在此页直接切换，须经治理评估后实施。",
        ["Content.SelfRegistrationAdminLoadFailed"] = "无法加载自助注册配置。",
        ["Content.SelfRegistrationAdminBadgeOpen"] = "已开放",
        ["Content.SelfRegistrationAdminBadgeClosed"] = "未开放",
        ["Content.CommonYes"] = "是",
        ["Content.CommonNo"] = "否",
        ["Content.AuditTitle"] = "审计日志",
        ["Content.AuditDesc"] = "记录关键操作与访问轨迹，支持按操作 / 资源 / 操作人 / 时间检索，满足合规要求。",
        ["Content.AuditSearchPlaceholder"] = "搜索操作 / 用户 / 资源…",
        ["Content.AuditEmptyTitle"] = "暂无审计记录",
        ["Content.AuditEmptyText"] = "关键写操作与登录事件会被记录到这里，便于追溯与合规审查。",
        ["Content.AuditLoadingText"] = "正在加载审计日志…",
        ["Content.AuditExportCsv"] = "导出 CSV",
        ["Content.AuditFilterAction"] = "操作 action",
        ["Content.AuditFilterEntity"] = "资源 entityType",
        ["Content.AuditFilterActor"] = "操作人 actor",
        ["Content.AuditReset"] = "重置",
        ["Content.AuditStatTotal"] = "日志总数",
        ["Content.AuditStatTotalSub"] = "本租户",
        ["Content.AuditStatFiltered"] = "筛选命中",
        ["Content.AuditStatFilteredSub"] = "当前条件",
        ["Content.AuditStatToday"] = "今日",
        ["Content.AuditStatTodaySub"] = "当天事件",
        ["Content.AuditNoExport"] = "没有可导出的记录。",
        ["Content.AuditExported"] = "已导出 {0} 条审计记录。",
        ["Content.CommonLoading"] = "加载中…",
        ["Content.SystemStatusDesc"] = "后端健康检查与运行时指标（只读）。",
        ["Content.SystemStatusRefreshing"] = "刷新中…",
        ["Content.SystemStatusHealthLabel"] = "健康状态",
        ["Content.SystemStatusRespLabel"] = "响应耗时",
        ["Content.SystemStatusRespSub"] = "本页刷新耗时",
        ["Content.SystemStatusMetricLabel"] = "指标行数",
        ["Content.SystemStatusMetricSub"] = "/metrics 文本行数",
        ["Content.SystemStatusTabHealth"] = "健康检查",
        ["Content.SystemStatusTabMetrics"] = "运行时指标",
        ["Content.SystemStatusNoResponse"] = "无响应",
        ["Content.DemoDataDesc"] = "安装独立的演示租户与示例业务数据（数据源/元数据/语义/仪表盘）。生产默认不安装，可重复安装受保护。",
        ["Content.DemoDataInstallStatus"] = "安装状态",
        ["Content.DemoDataColInstalled"] = "是否已安装",
        ["Content.DemoDataColTenant"] = "演示租户",
        ["Content.DemoDataColAdmin"] = "管理员账号",
        ["Content.DemoDataContentTitle"] = "将创建的内容",
        ["Content.DemoDataColType"] = "类型",
        ["Content.DemoDataColCount"] = "数量",
        ["Content.DemoDataColDesc"] = "说明",
        ["Content.DemoDataInstalledNote"] = "演示数据已安装，再次安装将被跳过（仅返回已有租户）。如需重建，请先删除演示租户。",
        ["Content.DemoDataInstalling"] = "正在安装演示数据…",
        ["Content.DemoDataConfirmText"] = "确认安装演示数据？将创建演示租户、管理员、数据源、元数据、业务语义与仪表盘，并写入多张业务表。",
        ["Content.DemoDataConfirmBtn"] = "确认安装",
        ["Content.DemoDataInstallBtn"] = "安装演示数据",
        ["Content.DemoDataDone"] = "演示数据安装完成。",
        ["Content.DemoDataLiTenant"] = "租户：",
        ["Content.DemoDataLiAdmin"] = "管理员：",
        ["Content.DemoDataLiPwd"] = "初始口令：",
        ["Content.DemoDataLiPwdNote"] = "（请妥善保存，首次登录后建议修改）",
        ["Content.DemoDataFailPrefix"] = "安装失败：",
        ["Content.DemoDataInstalledBadge"] = "已安装",
        ["Content.DemoDataNotInstalledBadge"] = "未安装",
        ["Content.DemoDataLoadFailed"] = "无法加载演示数据计划。",
        ["Content.DemoDataInstallError"] = "安装失败。",
        ["Content.SemanticLabelsTitle"] = "语义标签",
        ["Content.SemanticLabelsDesc"] = "为字段与指标打上业务标签，并维护同义词与召回策略，让问数更懂你的口径。",
        ["Content.SemanticLabelsSearchPlaceholder"] = "搜索标签 / 同义词…",
        ["Content.SemanticLabelsEmptyTitle"] = "暂无语义标签",
        ["Content.SemanticLabelsEmptyText"] = "语义标签把「GMV」「成交额」这类同义表述归一到统一口径，减少问数歧义。",
        ["Content.SemanticLabelsLoadingText"] = "正在加载语义标签…",
        ["Content.SemanticLabelsCreateBtn"] = "新建标签",
        ["Content.SemanticLabelsStatTotal"] = "标签总数",
        ["Content.SemanticLabelsStatEnabled"] = "已启用",
        ["Content.SemanticLabelsStatEnabledSub"] = "参与召回",
        ["Content.SemanticLabelsStatDisabled"] = "已停用",
        ["Content.SemanticLabelsStatDisabledSub"] = "不参与解析",
        ["Content.SemanticLabelsRowDetail"] = "详情",
        ["Content.SemanticLabelsModalTitle"] = "新建语义标签",
        ["Content.SemanticLabelsFieldConceptType"] = "概念类型",
        ["Content.SemanticLabelsCtMetadata"] = "字段级语义",
        ["Content.SemanticLabelsCtEntity"] = "业务实体",
        ["Content.SemanticLabelsCtEntityAttr"] = "业务实体属性",
        ["Content.SemanticLabelsCtEntityMetric"] = "业务实体指标",
        ["Content.SemanticLabelsCtDomain"] = "业务域",
        ["Content.SemanticLabelsFieldConceptId"] = "概念 ID",
        ["Content.SemanticLabelsConceptIdPh"] = "如：1001",
        ["Content.SemanticLabelsFieldCulture"] = "区域 (Culture)",
        ["Content.SemanticLabelsCulturePh"] = "如：zh-CN",
        ["Content.SemanticLabelsFieldKind"] = "标签种类",
        ["Content.SemanticLabelsKindDisplayName"] = "展示名",
        ["Content.SemanticLabelsKindDescription"] = "描述",
        ["Content.SemanticLabelsKindSynonym"] = "同义词",
        ["Content.SemanticLabelsKindQuestion"] = "示例问句",
        ["Content.SemanticLabelsFieldValue"] = "标签值",
        ["Content.SemanticLabelsValuePh"] = "如：销售额",
        ["Content.SemanticLabelsFieldSource"] = "来源",
        ["Content.SemanticLabelsSourcePh"] = "如：manual",
        ["Content.SemanticLabelsOpenNoId"] = "该记录缺少 id，无法打开详情。",
        ["Content.SemanticLabelsCidRequired"] = "概念 ID 必填。",
        ["Content.SemanticLabelsValueRequired"] = "标签值必填。",
        ["Content.SemanticLabelsCidNumeric"] = "概念 ID 必须为数字。",
        ["Content.SemanticLabelsSaveFailed"] = "保存失败。",
        ["Content.SemanticLabelsSaved"] = "语义标签已保存。",
        ["Content.AgentPlanDetailDesc"] = "智能体计划详情：目标、步骤序列与原始编排数据。",
        ["Content.AgentPlanDetailBack"] = "返回列表",
        ["Content.AgentPlanDetailDelete"] = "删除",
        ["Content.AgentPlanDetailLoadingText"] = "正在加载计划…",
        ["Content.AgentPlanDetailTabOverview"] = "概览",
        ["Content.AgentPlanDetailPanelInfo"] = "计划信息",
        ["Content.AgentPlanDetailTabSteps"] = "步骤",
        ["Content.AgentPlanDetailPanelSteps"] = "执行步骤",
        ["Content.AgentPlanDetailEmptyStepsTitle"] = "暂无步骤",
        ["Content.AgentPlanDetailEmptyStepsText"] = "该计划未包含可解析的步骤序列。",
        ["Content.AgentPlanDetailTabRaw"] = "原始数据",
        ["Content.AgentPlanDetailPanelRaw"] = "编排数据（只读）",
        ["Content.AgentPlanDetailConfirmTitle"] = "删除计划",
        ["Content.AgentPlanDetailConfirmMessage"] = "确认删除计划「{0}」？该操作不可撤销。",
        ["Content.AgentPlanDetailDefaultTitle"] = "计划详情",
        ["Content.AgentPlanDetailLoadFailed"] = "加载失败（{0}）。",
        ["Content.AgentPlanDetailStepN"] = "步骤 {0}",
        ["Content.AgentPlanDetailDeleted"] = "计划已删除。",
        ["Content.AgentPlanDetailDeleteFailed"] = "删除失败（{0}）。",
        ["Content.SelfRegistrationTagMultiTenant"] = "多租户",
        ["Content.SelfRegistrationTagLowCode"] = "低代码",
        ["Content.SelfRegistrationTagSaas"] = "企业级 SaaS",
        ["Content.SelfRegistrationChecking"] = "正在检查注册通道状态…",
        ["Content.SelfRegistrationClosedTitle"] = "注册通道未开放",
        ["Content.SelfRegistrationClosedDesc"] = "当前平台未开放自助注册。如需开通租户，请联系平台管理员。",
        ["Content.SelfRegistrationBackToLogin"] = "返回登录",
        ["Content.SelfRegistrationHasAccount"] = "已有账户？返回登录",
        ["Content.SelfRegistrationAlreadyLoggedIn"] = "当前已登录：{0}（租户 {1}）",
        ["Content.SelfRegistrationEnterWorkspace"] = "进入工作台",
        ["Content.SelfRegistrationApplyTitle"] = "申请开通新租户",
        ["Content.SelfRegistrationApplyDesc"] = "填写以下信息创建您的专属租户与首位管理员账户。",
        ["Content.SelfRegistrationLabelTenantCode"] = "租户编码（小写字母/数字，创建后不可变更）",
        ["Content.SelfRegistrationLabelTenantName"] = "租户名称",
        ["Content.SelfRegistrationLabelAdminUsername"] = "管理员用户名",
        ["Content.SelfRegistrationLabelAdminEmail"] = "管理员邮箱",
        ["Content.SelfRegistrationLabelAdminPassword"] = "管理员口令",
        ["Content.SelfRegistrationLabelConfirmPassword"] = "确认口令",
        ["Content.SelfRegistrationPhTenantName"] = "例如 Acme 科技",
        ["Content.SelfRegistrationPhPassword"] = "至少 8 位",
        ["Content.SelfRegistrationPhConfirmPassword"] = "再次输入口令",
        ["Content.SelfRegistrationSubmit"] = "创建租户并登录",
        ["Content.SelfRegistrationErrCodeNameRequired"] = "租户编码与名称均必填。",
        ["Content.SelfRegistrationErrAdminRequired"] = "管理员用户名与合法邮箱均必填。",
        ["Content.SelfRegistrationErrPasswordLen"] = "管理员口令至少 8 位。",
        ["Content.SelfRegistrationErrPasswordMismatch"] = "两次输入的口令不一致。",
        ["Content.SelfRegistrationErrFailed"] = "注册失败，请稍后重试。",
        ["Content.ProfileLogout"] = "退出登录",
        ["Content.ProfilePanelAccount"] = "账号信息",
        ["Content.ProfilePermissions"] = "权限",
        ["Content.ProfileNoExplicitPermission"] = "无显式权限",
        ["Content.ProfilePanelPreference"] = "界面偏好",
        ["Content.ProfileFieldTheme"] = "主题",
        ["Content.ProfileHintTheme"] = "偏好会保存在本地，下次进入自动应用。",
        ["Content.ProfileThemeDark"] = "深色",
        ["Content.ProfileThemeLight"] = "浅色",
        ["Content.ProfileUserId"] = "用户 ID",
        ["Content.ProfileTenantId"] = "租户 ID",
        ["Content.ProfileLoginStatus"] = "登录状态",
        ["Content.ProfileSignedIn"] = "已登录",
        ["Content.ProfileSignedOut"] = "未登录",
        ["Content.HomeStartAsk"] = "开始提问",
        ["Content.HomeStatDashboards"] = "仪表盘",
        ["Content.HomeStatDashboardsSub"] = "可复用看板",
        ["Content.HomeStatApps"] = "应用",
        ["Content.HomeStatAppsSub"] = "已发布的分析应用",
        ["Content.HomeStatLabels"] = "语义标签",
        ["Content.HomeStatLabelsSub"] = "业务口径映射",
        ["Content.HomeStatPlans"] = "智能体计划",
        ["Content.HomeStatPlansSub"] = "Copilot 编排",
        ["Content.HomeCardAskTitle"] = "Ask BI 智能问数",
        ["Content.HomeCardAskDesc"] = "用自然语言提问，自动完成语义解析、查询计划、SQL 生成与结果解读。",
        ["Content.HomeCardDashboardsTitle"] = "仪表盘",
        ["Content.HomeCardDashboardsDesc"] = "把一次分析固化为看板，支持图表组合、共享与定时刷新。",
        ["Content.HomeCardAppsTitle"] = "应用工厂",
        ["Content.HomeCardAppsDesc"] = "以 App DSL 描述页面与组件，一键生成可分发的轻量分析应用。",
        ["Content.HomeCardDataSourcesTitle"] = "数据源与授权",
        ["Content.HomeCardDataSourcesDesc"] = "登记业务库、配置访问授权与行级安全策略，控制可取数范围。",
        ["Content.HomePanelQuickStart"] = "快速开始",
        ["Content.HomeStep1"] = "在「数据源管理」登记业务库并完成连接测试。",
        ["Content.HomeStep2"] = "在「语义模型 / 语义标签」补齐业务口径，让 AI 听得懂行话。",
        ["Content.HomeStep3"] = "进入「Ask BI 智能问数」提问，检查结果与生成的 SQL。",
        ["Content.HomeStep4"] = "把满意的结果一键发布为仪表盘或应用。",
        ["Content.ThemeEditorSaveTheme"] = "主题",
        ["Content.ThemeEditorSampleReady"] = "就绪",

    };
}
