// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperBuilder_AI.Data;

#nullable disable

namespace SuperBuilder_AI.src.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SuperBIContext))]
    [Migration("20260901080848_AddRowLevelSecurityPolicies")]
    partial class AddRowLevelSecurityPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperBuilder_AI.Models.Agent.AgentPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("业务编码");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("描述");

                    b.Property<string>("DslJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("DSL文档（结构化，非裸HTML）");

                    b.Property<string>("DslVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComment("DSL版本");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("名称");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("状态");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=全局模板）");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("AgentPlans", t =>
                        {
                            t.HasComment("Agent计划");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.AppBuilder.AppPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("业务编码");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("描述");

                    b.Property<string>("DslJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("DSL文档（结构化，非裸HTML）");

                    b.Property<string>("DslVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComment("DSL版本");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("名称");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("状态");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=全局模板）");

                    b.Property<string>("ThemeKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主题键");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("AppPlans", t =>
                        {
                            t.HasComment("应用");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("动作类型");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("操作者标识");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("实体Id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("实体类型");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("结果");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=平台级）");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TenantId", "Action");

                    b.HasIndex("TenantId", "EntityType");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasComment("审计日志");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessDomains", null, t =>
                        {
                            t.HasComment("业务域");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BusinessDomainId")
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SemanticText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDomainId");

                    b.HasIndex("TenantId", "BusinessKey")
                        .IsUnique();

                    b.ToTable("BusinessEntities", null, t =>
                        {
                            t.HasComment("业务实体");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIdentifier")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SemanticType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId", "IsIdentifier");

                    b.HasIndex("BusinessEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityAttributes", null, t =>
                        {
                            t.HasComment("业务实体属性");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityDimension", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessDomainId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDomainId");

                    b.HasIndex("TenantId", "BusinessDomainId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityDimensions", null, t =>
                        {
                            t.HasComment("业务实体维度");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("KeyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId", "IsPrimary");

                    b.HasIndex("BusinessEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityKeys", null, t =>
                        {
                            t.HasComment("业务实体键");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aggregation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("BusinessEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SemanticType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityMetrics", null, t =>
                        {
                            t.HasComment("业务实体指标");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cardinality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SourceEntityId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetEntityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TargetEntityId");

                    b.HasIndex("SourceEntityId", "TargetEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityRelationships", null, t =>
                        {
                            t.HasComment("业务实体关系");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.PhysicalBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BindingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("BusinessEntityAttributeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusinessEntityKeyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusinessEntityMetricId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusinessEntityRelationshipId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<long>("MetadataTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhysicalRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetadataColumnId");

                    b.HasIndex("MetadataTableId");

                    b.HasIndex("BusinessEntityAttributeId", "IsActive");

                    b.HasIndex("BusinessEntityKeyId", "IsActive");

                    b.HasIndex("BusinessEntityMetricId", "IsActive");

                    b.HasIndex("BusinessEntityRelationshipId", "PhysicalRole", "IsActive");

                    b.HasIndex("DataSourceId", "MetadataTableId", "MetadataColumnId", "Priority");

                    b.ToTable("PhysicalBindings", null, t =>
                        {
                            t.HasComment("业务语义到物理元数据的映射");

                            t.HasCheckConstraint("CK_PhysicalBindings_ExactlyOneOwner", "((CASE WHEN BusinessEntityKeyId IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN BusinessEntityAttributeId IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN BusinessEntityMetricId IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN BusinessEntityRelationshipId IS NOT NULL THEN 1 ELSE 0 END)) = 1");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Dashboard.Dashboard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("业务编码");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasComment("描述");

                    b.Property<string>("DslJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("DSL文档（结构化，非裸HTML）");

                    b.Property<string>("DslVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComment("DSL版本");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("状态");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=全局模板）");

                    b.Property<string>("ThemeKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主题键");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("标题");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Dashboards", t =>
                        {
                            t.HasComment("仪表盘");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.DataSourceAccessGrant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId");

                    b.HasIndex("TenantId", "DataSourceId", "SubjectType", "SubjectId")
                        .IsUnique();

                    b.ToTable("DataSourceAccessGrants", (string)null);
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("权限分类");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("权限码（同租户唯一）");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("权限名");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=全局权限）");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Permissions", t =>
                        {
                            t.HasComment("权限");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("角色码（同租户唯一）");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("角色名");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=全局角色）");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Roles", t =>
                        {
                            t.HasComment("角色");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", t =>
                        {
                            t.HasComment("角色-权限关联");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.RowLevelSecurityPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<long>("MetadataTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<string>("SubjectValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("MetadataColumnId");

                    b.HasIndex("MetadataTableId");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId");

                    b.HasIndex("TenantId", "DataSourceId", "MetadataTableId", "Enabled");

                    b.ToTable("RowLevelSecurityPolicies", (string)null);
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("显示名");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("邮箱");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("口令哈希（PBKDF2，可选）");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("安全戳（令牌吊销用）");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("状态");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("登录名（全局唯一）");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("用户");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", t =>
                        {
                            t.HasComment("用户-角色关联");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Localization.SemanticLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConceptId")
                        .HasColumnType("bigint")
                        .HasComment("概念实体Id");

                    b.Property<string>("ConceptType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("概念类型");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComment("语言标签");

                    b.Property<string>("LabelKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("标签种类");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("来源");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=全局共享）");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("标签文本");

                    b.HasKey("Id");

                    b.HasIndex("ConceptType", "ConceptId", "Culture");

                    b.HasIndex("TenantId", "ConceptType", "ConceptId", "Culture", "LabelKind", "SortOrder")
                        .IsUnique();

                    b.ToTable("SemanticLabels", t =>
                        {
                            t.HasComment("语义多语言标签");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("连接字符串");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DbType")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("数据库类型");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("DataSources", t =>
                        {
                            t.HasComment("数据源");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessKey")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段业务唯一标识");

                    b.Property<string>("ColumnComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<long?>("Length")
                        .HasColumnType("bigint");

                    b.Property<long?>("MetadataTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段Embedding文本");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant字段向量ID");

                    b.HasKey("Id");

                    b.HasIndex("MetadataTableId", "ColumnName")
                        .IsUnique()
                        .HasFilter("[MetadataTableId] IS NOT NULL AND [ColumnName] IS NOT NULL");

                    b.ToTable("MetadataColumns", t =>
                        {
                            t.HasComment("元数据字段");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataLearningRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Correct")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LearningRecords", t =>
                        {
                            t.HasComment("学习记录");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataSemantic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务域");

                    b.Property<string>("BusinessMeaning")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务含义");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleQuestions")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("示例问题");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("关键词");

                    b.Property<long?>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("语义Embedding文本");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("来源");

                    b.Property<string>("Synonyms")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("同义词");

                    b.Property<int?>("VectorDimension")
                        .HasColumnType("int");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant语义向量ID");

                    b.HasKey("Id");

                    b.HasIndex("MetadataColumnId")
                        .IsUnique()
                        .HasFilter("[MetadataColumnId] IS NOT NULL");

                    b.ToTable("MetadataSemantics", t =>
                        {
                            t.HasComment("字段AI语义");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Embedding文本");

                    b.Property<string>("TableComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int?>("VectorDimension")
                        .HasColumnType("int");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant向量ID");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "TableName")
                        .IsUnique()
                        .HasFilter("[TableName] IS NOT NULL");

                    b.ToTable("MetadataTables", t =>
                        {
                            t.HasComment("元数据表");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasComment("是否启用");

                    b.Property<string>("TenantCode")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("租户编码");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("租户名称");

                    b.HasKey("Id");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasFilter("[TenantCode] IS NOT NULL");

                    b.ToTable("Tenants", t =>
                        {
                            t.HasComment("租户");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.TenantSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DataType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("值类型");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("配置键");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("配置值");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("TenantSettings", t =>
                        {
                            t.HasComment("租户键值配置");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Quota.QuotaPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Limit")
                        .HasColumnType("bigint")
                        .HasComment("上限");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int")
                        .HasComment("资源类型");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=平台默认）");

                    b.Property<int>("Window")
                        .HasColumnType("int")
                        .HasComment("周期窗口");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ResourceType")
                        .IsUnique();

                    b.ToTable("QuotaPolicies", t =>
                        {
                            t.HasComment("配额策略");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Quota.QuotaUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<DateTime>("LastReset")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("周期键");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int")
                        .HasComment("资源类型");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户");

                    b.Property<long>("Used")
                        .HasColumnType("bigint")
                        .HasComment("已用");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ResourceType")
                        .IsUnique();

                    b.ToTable("QuotaUsages", t =>
                        {
                            t.HasComment("配额使用量");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Theme.Theme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DslJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("主题DSL文档（结构化令牌，非CSS/HTML）");

                    b.Property<string>("DslVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComment("DSL版本");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit")
                        .HasComment("是否内置主题");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("主题键（同租户内唯一）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("主题名称");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasComment("所属租户（0=内置/全局模板）");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("Themes", t =>
                        {
                            t.HasComment("主题");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", "Domain")
                        .WithMany("Entities")
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "BusinessEntity")
                        .WithMany("Attributes")
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityDimension", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", "Domain")
                        .WithMany("Dimensions")
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "BusinessEntity")
                        .WithMany("Keys")
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "BusinessEntity")
                        .WithMany("Metrics")
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "SourceEntity")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "TargetEntity")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEntity");

                    b.Navigation("TargetEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.PhysicalBinding", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", "BusinessEntityAttribute")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityAttributeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", "BusinessEntityKey")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityKeyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", "BusinessEntityMetric")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityMetricId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", "BusinessEntityRelationship")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityRelationshipId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.Metadata.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataColumn", "MetadataColumn")
                        .WithMany()
                        .HasForeignKey("MetadataColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataTable", "MetadataTable")
                        .WithMany()
                        .HasForeignKey("MetadataTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessEntityAttribute");

                    b.Navigation("BusinessEntityKey");

                    b.Navigation("BusinessEntityMetric");

                    b.Navigation("BusinessEntityRelationship");

                    b.Navigation("DataSource");

                    b.Navigation("MetadataColumn");

                    b.Navigation("MetadataTable");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.DataSourceAccessGrant", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Identity.RowLevelSecurityPolicy", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataColumn", null)
                        .WithMany()
                        .HasForeignKey("MetadataColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataTable", null)
                        .WithMany()
                        .HasForeignKey("MetadataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.DataSource", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany("DataSources")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataTable", "MetadataTable")
                        .WithMany("Columns")
                        .HasForeignKey("MetadataTableId");

                    b.Navigation("MetadataTable");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataSemantic", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataColumn", "MetadataColumn")
                        .WithOne("Semantic")
                        .HasForeignKey("SuperBuilder_AI.Models.Metadata.MetadataSemantic", "MetadataColumnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MetadataColumn");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.DataSource", "DataSource")
                        .WithMany("Tables")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.TenantSetting", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("Entities");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Keys");

                    b.Navigation("Metrics");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.DataSource", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.Navigation("Semantic");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.Tenant", b =>
                {
                    b.Navigation("DataSources");
                });
#pragma warning restore 612, 618
        }
    }
}
