// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperBuilder_AI.Data;

#nullable disable

namespace SuperBuilder_AI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SuperBIContext))]
    [Migration("20260829090341_P4_2_TenantSettings")]
    partial class P4_2_TenantSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessDomains", null, t =>
                        {
                            t.HasComment("业务域");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BusinessDomainId")
                        .HasColumnType("bigint");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SemanticText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDomainId");

                    b.HasIndex("TenantId", "BusinessKey")
                        .IsUnique();

                    b.ToTable("BusinessEntities", null, t =>
                        {
                            t.HasComment("业务实体");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIdentifier")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SemanticType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId", "IsIdentifier");

                    b.HasIndex("BusinessEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityAttributes", null, t =>
                        {
                            t.HasComment("业务实体属性");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityDimension", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessDomainId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDomainId");

                    b.HasIndex("TenantId", "BusinessDomainId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityDimensions", null, t =>
                        {
                            t.HasComment("业务实体维度");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BusinessEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("KeyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId", "IsPrimary");

                    b.HasIndex("BusinessEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityKeys", null, t =>
                        {
                            t.HasComment("业务实体键");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aggregation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("BusinessEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SemanticType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityMetrics", null, t =>
                        {
                            t.HasComment("业务实体指标");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cardinality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SourceEntityId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetEntityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TargetEntityId");

                    b.HasIndex("SourceEntityId", "TargetEntityId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessEntityRelationships", null, t =>
                        {
                            t.HasComment("业务实体关系");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.PhysicalBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BindingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("BusinessEntityAttributeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusinessEntityKeyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusinessEntityMetricId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BusinessEntityRelationshipId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<long>("MetadataTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhysicalRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetadataColumnId");

                    b.HasIndex("MetadataTableId");

                    b.HasIndex("BusinessEntityAttributeId", "IsActive");

                    b.HasIndex("BusinessEntityKeyId", "IsActive");

                    b.HasIndex("BusinessEntityMetricId", "IsActive");

                    b.HasIndex("BusinessEntityRelationshipId", "PhysicalRole", "IsActive");

                    b.HasIndex("DataSourceId", "MetadataTableId", "MetadataColumnId", "Priority");

                    b.ToTable("PhysicalBindings", null, t =>
                        {
                            t.HasComment("业务语义到物理元数据的映射");

                            t.HasCheckConstraint("CK_PhysicalBindings_ExactlyOneOwner", "((CASE WHEN BusinessEntityKeyId IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN BusinessEntityAttributeId IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN BusinessEntityMetricId IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN BusinessEntityRelationshipId IS NOT NULL THEN 1 ELSE 0 END)) = 1");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("连接字符串");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DbType")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("数据库类型");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("DataSources", t =>
                        {
                            t.HasComment("数据源");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessKey")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段业务唯一标识");

                    b.Property<string>("ColumnComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<long?>("Length")
                        .HasColumnType("bigint");

                    b.Property<long?>("MetadataTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("字段Embedding文本");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant字段向量ID");

                    b.HasKey("Id");

                    b.HasIndex("MetadataTableId", "ColumnName")
                        .IsUnique()
                        .HasFilter("[MetadataTableId] IS NOT NULL AND [ColumnName] IS NOT NULL");

                    b.ToTable("MetadataColumns", t =>
                        {
                            t.HasComment("元数据字段");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataLearningRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Correct")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LearningRecords", t =>
                        {
                            t.HasComment("学习记录");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataSemantic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务域");

                    b.Property<string>("BusinessMeaning")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("业务含义");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleQuestions")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("示例问题");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("关键词");

                    b.Property<long?>("MetadataColumnId")
                        .HasColumnType("bigint");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("语义Embedding文本");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("来源");

                    b.Property<string>("Synonyms")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("同义词");

                    b.Property<int?>("VectorDimension")
                        .HasColumnType("int");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant语义向量ID");

                    b.HasKey("Id");

                    b.HasIndex("MetadataColumnId")
                        .IsUnique()
                        .HasFilter("[MetadataColumnId] IS NOT NULL");

                    b.ToTable("MetadataSemantics", t =>
                        {
                            t.HasComment("字段AI语义");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchText")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Embedding文本");

                    b.Property<string>("TableComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int?>("VectorDimension")
                        .HasColumnType("int");

                    b.Property<string>("VectorId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Qdrant向量ID");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "TableName")
                        .IsUnique()
                        .HasFilter("[TableName] IS NOT NULL");

                    b.ToTable("MetadataTables", t =>
                        {
                            t.HasComment("元数据表");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasComment("是否启用");

                    b.Property<string>("TenantCode")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("租户编码");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("租户名称");

                    b.HasKey("Id");

                    b.HasIndex("TenantCode")
                        .IsUnique()
                        .HasFilter("[TenantCode] IS NOT NULL");

                    b.ToTable("Tenants", t =>
                        {
                            t.HasComment("租户");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.TenantSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("DataType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasComment("值类型");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasComment("配置键");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("配置值");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("TenantSettings", t =>
                        {
                            t.HasComment("租户键值配置");
                        });
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", "Domain")
                        .WithMany("Entities")
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "BusinessEntity")
                        .WithMany("Attributes")
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityDimension", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", "Domain")
                        .WithMany("Dimensions")
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "BusinessEntity")
                        .WithMany("Keys")
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "BusinessEntity")
                        .WithMany("Metrics")
                        .HasForeignKey("BusinessEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "SourceEntity")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", "TargetEntity")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEntity");

                    b.Navigation("TargetEntity");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.PhysicalBinding", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", "BusinessEntityAttribute")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityAttributeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", "BusinessEntityKey")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityKeyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", "BusinessEntityMetric")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityMetricId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", "BusinessEntityRelationship")
                        .WithMany("PhysicalBindings")
                        .HasForeignKey("BusinessEntityRelationshipId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuperBuilder_AI.Models.Metadata.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataColumn", "MetadataColumn")
                        .WithMany()
                        .HasForeignKey("MetadataColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataTable", "MetadataTable")
                        .WithMany()
                        .HasForeignKey("MetadataTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessEntityAttribute");

                    b.Navigation("BusinessEntityKey");

                    b.Navigation("BusinessEntityMetric");

                    b.Navigation("BusinessEntityRelationship");

                    b.Navigation("DataSource");

                    b.Navigation("MetadataColumn");

                    b.Navigation("MetadataTable");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.DataSource", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany("DataSources")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataTable", "MetadataTable")
                        .WithMany("Columns")
                        .HasForeignKey("MetadataTableId");

                    b.Navigation("MetadataTable");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataSemantic", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.MetadataColumn", "MetadataColumn")
                        .WithOne("Semantic")
                        .HasForeignKey("SuperBuilder_AI.Models.Metadata.MetadataSemantic", "MetadataColumnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MetadataColumn");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Metadata.DataSource", "DataSource")
                        .WithMany("Tables")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.TenantSetting", b =>
                {
                    b.HasOne("SuperBuilder_AI.Models.Organization.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessDomain", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("Entities");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntity", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Keys");

                    b.Navigation("Metrics");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityAttribute", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityKey", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityMetric", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.BI.Entity.BusinessEntityRelationship", b =>
                {
                    b.Navigation("PhysicalBindings");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.DataSource", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataColumn", b =>
                {
                    b.Navigation("Semantic");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Metadata.MetadataTable", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("SuperBuilder_AI.Models.Organization.Tenant", b =>
                {
                    b.Navigation("DataSources");
                });
#pragma warning restore 612, 618
        }
    }
}
